/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActorType = { 'Student' : null } |
  { 'Admin' : null };
export type AdminLoginResult = {
    'ok' : { 'token' : string, 'expiresAt' : Timestamp }
  } |
  { 'err' : string };
export interface AnalyticsData {
  'returnedRequests' : bigint,
  'requestsOverTime' : Array<[string, bigint]>,
  'waitingListCount' : bigint,
  'rejectedRequests' : bigint,
  'activeStudents' : bigint,
  'totalProcurements' : bigint,
  'totalStudents' : bigint,
  'totalReservations' : bigint,
  'booksIssued' : bigint,
  'pendingRequests' : bigint,
  'approvedRequests' : bigint,
  'booksAvailable' : bigint,
  'lowStockBooks' : bigint,
  'reservedBooks' : bigint,
  'totalBooks' : bigint,
  'booksOverdue' : bigint,
  'booksByCategory' : Array<[string, bigint]>,
  'dueReturns' : bigint,
}
export type AuditAction = { 'BookRequest' : null } |
  { 'RequestOpened' : null } |
  { 'ChallanGenerated' : null } |
  { 'BookIssue' : null } |
  { 'ProfileUpdate' : null } |
  { 'NotificationSent' : null } |
  { 'BookReturn' : null } |
  { 'ReservationCreation' : null } |
  { 'BookReserved' : null } |
  { 'RequestFinalized' : null } |
  { 'CollectionOrderGenerated' : null } |
  { 'StudentRegistration' : null } |
  { 'BookRejection' : null } |
  { 'BookApproval' : null } |
  { 'BookCollected' : null } |
  { 'AdminChange' : null } |
  { 'CollectionDateAssigned' : null };
export interface AuditBookDecision {
  'status' : BookDecisionStatus,
  'bookNumber' : string,
  'bookName' : string,
  'author' : string,
  'reason' : [] | [string],
}
export interface AuditEntry {
  'id' : string,
  'action' : AuditAction,
  'actorName' : [] | [string],
  'actorType' : ActorType,
  'studentName' : [] | [string],
  'resourceId' : string,
  'requestNumber' : [] | [string],
  'actorId' : string,
  'adminName' : [] | [string],
  'resourceType' : [] | [string],
  'bookDecisions' : Array<AuditBookDecision>,
  'timestamp' : Timestamp,
  'details' : [] | [string],
  'userAgent' : [] | [string],
  'ipAddress' : [] | [string],
}
export interface AuthResult {
  'token' : string,
  'userId' : string,
  'user' : UserPublic,
}
export interface Book {
  'title' : string,
  'isDeleted' : boolean,
  'edition' : string,
  'availableQuantity' : bigint,
  'publisher' : string,
  'createdAt' : Timestamp,
  'waitingQueue' : Array<UserId>,
  'isAvailable' : boolean,
  'bookId' : BookId,
  'availableCount' : bigint,
  'author' : string,
  'quantity' : bigint,
  'category' : string,
  'currentHolders' : Array<UserId>,
  'totalQuantity' : bigint,
}
export interface BookAvailabilityDate {
  'bookTitle' : string,
  'bookId' : BookId,
  'expectedDate' : Timestamp,
}
export interface BookCsvRow {
  'title' : string,
  'availableCopies' : bigint,
  'edition' : string,
  'publisher' : string,
  'author' : string,
  'totalCopies' : bigint,
  'category' : string,
}
export interface BookDecision {
  'decision' : BookDecisionStatus,
  'bookNumber' : string,
  'bookName' : string,
  'edition' : string,
  'subject' : string,
  'publisher' : string,
  'procurementId' : [] | [ProcurementId],
  'currentHolderStudentId' : [] | [string],
  'bookId' : BookId,
  'queuePosition' : [] | [bigint],
  'author' : string,
  'procurementCreated' : boolean,
  'expectedReturnDate' : [] | [Timestamp],
  'currentHolder' : [] | [string],
  'inventoryId' : string,
  'reason' : [] | [string],
}
export type BookDecisionStatus = { 'Arrived' : null } |
  { 'Reserved' : null } |
  { 'Ordered' : null } |
  { 'Purchased' : null } |
  { 'SpecialOrder' : null } |
  { 'ReadyForCollection' : null } |
  { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Issued' : null } |
  { 'Returned' : null } |
  { 'Pending' : null };
export interface BookDetailView {
  'title' : string,
  'decision' : [] | [BookDecision],
  'bookNumber' : string,
  'edition' : string,
  'subject' : string,
  'publisher' : string,
  'queueLength' : bigint,
  'bookId' : BookId,
  'author' : string,
  'expectedReturnDate' : [] | [Timestamp],
  'currentHolder' : [] | [string],
  'inventoryId' : string,
  'availabilityStatus' : string,
}
export type BookId = string;
export interface BookInput {
  'title' : string,
  'edition' : string,
  'publisher' : string,
  'author' : string,
  'quantity' : bigint,
  'category' : string,
}
export interface BookRequest {
  'issueDate' : [] | [Timestamp],
  'status' : string,
  'bookApprovals' : Array<[BookId, string]>,
  'studentEmail' : string,
  'studentAadhaar' : string,
  'requestId' : RequestId,
  'studentId' : string,
  'studentName' : string,
  'studentYear' : string,
  'challanId' : [] | [ChallanId],
  'requestNotes' : [] | [string],
  'userId' : UserId,
  'specialRequests' : Array<SpecialRequest>,
  'createdAt' : Timestamp,
  'requestedBooks' : Array<RequestedBookPublic>,
  'studentPhone' : string,
  'requestNumber' : string,
  'collectionOrderId' : [] | [string],
  'adminName' : [] | [string],
  'updatedAt' : Timestamp,
  'bookDecisions' : Array<BookDecision>,
  'adminId' : [] | [string],
  'studentCourse' : string,
  'challanData' : string,
  'returnDate' : [] | [Timestamp],
  'returned' : boolean,
  'selectedBookIds' : Array<BookId>,
  'collectionDate' : string,
  'collectionLocation' : string,
  'collectionTime' : string,
}
export interface Challan {
  'challanNumber' : string,
  'trackingEvents' : Array<string>,
  'status' : string,
  'studentEmail' : string,
  'signatureAdmin' : [] | [string],
  'signatureStudent' : [] | [string],
  'procurementRequests' : Array<ProcurementRequest>,
  'studentId' : UserId,
  'qrCodeData' : [] | [string],
  'studentName' : string,
  'studentYear' : string,
  'challanId' : ChallanId,
  'reservations' : Array<Reservation>,
  'trackedBookIds' : Array<BookId>,
  'generatedAt' : Timestamp,
  'specialRequests' : Array<SpecialRequest>,
  'createdAt' : Timestamp,
  'availabilityDates' : Array<BookAvailabilityDate>,
  'studentPhone' : string,
  'requestNumber' : RequestId,
  'orderedBooks' : Array<ChallanBookEntry>,
  'rejectedBooks' : Array<ChallanBookEntry>,
  'returnedBooks' : Array<ChallanBookEntry>,
  'arrivedBooks' : Array<ChallanBookEntry>,
  'adminName' : string,
  'totalAmount' : bigint,
  'bookDecisions' : Array<BookDecision>,
  'pdfUrl' : [] | [string],
  'qrCodeUrl' : string,
  'approvedBooks' : Array<ChallanBookEntry>,
  'reservedBooks' : Array<ChallanBookEntry>,
  'manualBooks' : Array<ChallanBookEntry>,
  'collectionOrderNumber' : string,
  'issuedBookIds' : Array<BookId>,
  'studentCourse' : string,
  'issuedBooks' : Array<ChallanBookEntry>,
  'readyForCollectionBooks' : Array<ChallanBookEntry>,
  'expectedDates' : Array<BookAvailabilityDate>,
  'collectionDate' : string,
  'collectionTime' : string,
}
export interface ChallanBookEntry {
  'status' : BookDecisionStatus,
  'title' : string,
  'bookNumber' : string,
  'edition' : string,
  'subject' : string,
  'publisher' : string,
  'currentHolderStudentId' : [] | [string],
  'bookId' : BookId,
  'queuePosition' : [] | [bigint],
  'author' : string,
  'expectedAvailabilityDate' : [] | [Timestamp],
  'expectedReturnDate' : [] | [Timestamp],
  'currentHolder' : [] | [string],
  'reason' : [] | [string],
}
export type ChallanId = string;
export interface ChallanPdfData {
  'adminSignaturePlaceholder' : string,
  'studentSignaturePlaceholder' : string,
  'qrCodeUrl' : string,
  'collectionOrderNumber' : string,
  'challan' : Challan,
  'collectionDate' : string,
  'collectionLocation' : string,
  'collectionTime' : string,
}
export interface CollectionEntry {
  'bookTitle' : string,
  'requestId' : RequestId,
  'studentId' : UserId,
  'studentName' : string,
  'bookId' : BookId,
  'collectionDeadline' : Timestamp,
  'approvalDate' : Timestamp,
  'entryId' : string,
  'collected' : boolean,
}
export interface CollectionOrder {
  'status' : { 'Collected' : null } |
    { 'Cancelled' : null } |
    { 'Completed' : null } |
    { 'Pending' : null },
  'studentEmail' : string,
  'requestId' : RequestId,
  'studentId' : UserId,
  'studentName' : string,
  'studentYear' : string,
  'challanId' : [] | [ChallanId],
  'generatedAt' : Timestamp,
  'specialRequests' : Array<SpecialRequest>,
  'studentPhone' : string,
  'orderedBooks' : Array<BookDecision>,
  'rejectedBooks' : Array<BookDecision>,
  'orderId' : string,
  'returnedBooks' : Array<BookDecision>,
  'arrivedBooks' : Array<BookDecision>,
  'adminName' : string,
  'bookDecisions' : Array<BookDecision>,
  'approvedBooks' : Array<BookDecision>,
  'reservedBooks' : Array<BookDecision>,
  'studentCourse' : string,
  'issuedBooks' : Array<BookDecision>,
  'orderNumber' : string,
  'readyForCollectionBooks' : Array<BookDecision>,
  'collectionDate' : string,
  'collectionLocation' : string,
  'collectionTime' : string,
}
export type CollectionOrderId = string;
export interface CompleteApprovalResult {
  'collectionOrder' : CollectionOrder,
  'request' : BookRequest,
  'challan' : Challan,
}
export interface CsvImportResult {
  'skipped' : bigint,
  'errors' : Array<string>,
  'processed' : bigint,
}
export type DeliveryStatus = { 'Failed' : null } |
  { 'Demo' : null } |
  { 'Sent' : null } |
  { 'Pending' : null };
export interface EmailSendResult {
  'messageId' : [] | [string],
  'sentAt' : Timestamp,
  'error' : [] | [string],
  'success' : boolean,
}
export interface IssuedBookInfo {
  'bookTitle' : string,
  'issueDate' : Timestamp,
  'status' : string,
  'requestId' : RequestId,
  'studentName' : string,
  'userId' : UserId,
  'bookId' : BookId,
  'bookIds' : Array<BookId>,
  'expectedReturnDate' : Timestamp,
  'returnDate' : [] | [Timestamp],
  'returned' : boolean,
}
export type MembershipStatus = { 'PAID' : null } |
  { 'NOT_PAID' : null };
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'actionUrl' : [] | [string],
  'userId' : string,
  'kind' : NotificationKind,
  'deliveryStatus' : Array<NotificationDeliveryStatus>,
  'isRead' : boolean,
  'challanUrl' : [] | [string],
  'message' : string,
  'timestamp' : Timestamp,
  'emailSent' : boolean,
  'bookOutcomes' : Array<NotificationBookOutcome>,
  'collectionDate' : [] | [string],
  'collectionLocation' : [] | [string],
  'collectionTime' : [] | [string],
  'eventType' : [] | [string],
  'readAt' : [] | [Timestamp],
}
export interface NotificationBookOutcome {
  'status' : BookDecisionStatus,
  'bookNumber' : string,
  'bookName' : string,
  'edition' : string,
  'author' : string,
  'expectedAvailabilityDate' : [] | [Timestamp],
  'expectedReturnDate' : [] | [Timestamp],
  'currentHolder' : [] | [string],
  'reason' : [] | [string],
}
export type NotificationChannel = { 'SMS' : null } |
  { 'Email' : null } |
  { 'WhatsApp' : null } |
  { 'Website' : null };
export interface NotificationDeliveryStatus {
  'status' : DeliveryStatus,
  'sentAt' : [] | [Timestamp],
  'error' : [] | [string],
  'channel' : NotificationChannel,
}
export type NotificationEventType = string;
export type NotificationId = string;
export type NotificationKind = { 'BookReadyForCollection' : null } |
  { 'ReturnAlert' : null } |
  { 'CourseCompletion' : null } |
  { 'PaymentSuccess' : null } |
  { 'QueueUpdate' : null } |
  { 'RegistrationSuccess' : null } |
  { 'ChallanGenerated' : null } |
  { 'General' : null } |
  { 'BookReserved' : null } |
  { 'ProcurementNeeded' : null } |
  { 'DueDateReminder' : null } |
  { 'BookApproved' : null } |
  { 'ReservationFulfilled' : null } |
  { 'BookAvailable' : null } |
  { 'YearPromotion' : null } |
  { 'BookTransferred' : null } |
  { 'ReturnReminder' : null } |
  { 'BookRejected' : null };
export interface Payment {
  'status' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'paymentId' : PaymentId,
  'stripePaymentId' : string,
  'amount' : bigint,
}
export type PaymentId = string;
export type ProcurementId = string;
export interface ProcurementRequest {
  'id' : ProcurementId,
  'bookTitle' : string,
  'status' : ProcurementStatus,
  'studentId' : UserId,
  'edition' : [] | [string],
  'urgency' : ProcurementUrgency,
  'publisher' : [] | [string],
  'bookId' : [] | [BookId],
  'author' : [] | [string],
  'requestDate' : Timestamp,
}
export type ProcurementStatus = { 'Procured' : null } |
  { 'Ordered' : null } |
  { 'ReadyForCollection' : null } |
  { 'Approved' : null } |
  { 'Issued' : null } |
  { 'Cancelled' : null } |
  { 'Returned' : null } |
  { 'Pending' : null };
export type ProcurementUrgency = { 'Required' : null } |
  { 'Optional' : null };
export interface ProviderConfig {
  'whatsAppApiKey' : [] | [string],
  'whatsAppProvider' : [] | [WhatsAppProvider],
  'smsSenderId' : [] | [string],
  'smsProvider' : [] | [SmsProvider],
  'smsApiKey' : [] | [string],
  'whatsAppSenderId' : [] | [string],
}
export interface RequestDetails {
  'request' : BookRequest,
  'specialRequests' : Array<SpecialRequest>,
  'student' : UserPublic,
  'books' : Array<BookDetailView>,
}
export type RequestId = string;
export interface RequestOutcome {
  'requestId' : RequestId,
  'challanId' : [] | [ChallanId],
  'requestNumber' : string,
  'rejectedBooks' : Array<BookDecision>,
  'collectionOrderId' : [] | [string],
  'approvedBooks' : Array<BookDecision>,
  'reservedBooks' : Array<BookDecision>,
  'overallStatus' : string,
  'collectionDate' : string,
  'collectionLocation' : string,
  'collectionTime' : string,
}
export interface RequestedBookPublic {
  'title' : string,
  'edition' : string,
  'publisher' : string,
  'author' : string,
  'imageUrl' : string,
}
export interface Reservation {
  'id' : ReservationId,
  'status' : ReservationStatus,
  'studentId' : UserId,
  'bookId' : BookId,
  'expectedAvailabilityDate' : [] | [Timestamp],
  'requestDate' : Timestamp,
}
export type ReservationId = string;
export type ReservationStatus = { 'Waiting' : null } |
  { 'Cancelled' : null } |
  { 'Fulfilled' : null };
export type Result = { 'ok' : WaitingListAssignment } |
  { 'err' : string };
export type Result_1 = { 'ok' : AuthResult } |
  { 'err' : string };
export type Result_10 = { 'ok' : EmailSendResult } |
  { 'err' : string };
export type Result_11 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_12 = {
    'ok' : { 'reservation' : Reservation, 'queuePosition' : bigint }
  } |
  { 'err' : string };
export type Result_13 = { 'ok' : SpecialRequest } |
  { 'err' : string };
export type Result_14 = { 'ok' : BookDecision } |
  { 'err' : string };
export type Result_15 = { 'ok' : Payment } |
  { 'err' : string };
export type Result_16 = { 'ok' : string } |
  { 'err' : string };
export type Result_17 = { 'ok' : CsvImportResult } |
  { 'err' : string };
export type Result_18 = { 'ok' : RequestDetails } |
  { 'err' : string };
export type Result_19 = {
    'ok' : {
      'pending' : bigint,
      'demo' : bigint,
      'sent' : bigint,
      'failed' : bigint,
    }
  } |
  { 'err' : string };
export type Result_2 = { 'ok' : UserPublic } |
  { 'err' : string };
export type Result_20 = {
    'ok' : {
      'demoMode' : boolean,
      'whatsAppConfigured' : boolean,
      'smsConfigured' : boolean,
    }
  } |
  { 'err' : string };
export type Result_21 = { 'ok' : RequestOutcome } |
  { 'err' : string };
export type Result_22 = { 'ok' : CollectionOrder } |
  { 'err' : string };
export type Result_23 = { 'ok' : ChallanPdfData } |
  { 'err' : string };
export type Result_24 = { 'ok' : Challan } |
  { 'err' : string };
export type Result_25 = { 'ok' : Array<AuditEntry> } |
  { 'err' : string };
export type Result_26 = { 'ok' : CompleteApprovalResult } |
  { 'err' : string };
export type Result_27 = { 'ok' : ProcurementRequest } |
  { 'err' : string };
export type Result_28 = { 'ok' : Reservation } |
  { 'err' : string };
export type Result_29 = {
    'ok' : {
      'waitingCount' : bigint,
      'available' : boolean,
      'expectedReturnDate' : [] | [Timestamp],
      'daysUntilReturn' : [] | [bigint],
    }
  } |
  { 'err' : string };
export type Result_3 = { 'ok' : BookRequest } |
  { 'err' : string };
export type Result_4 = { 'ok' : null } |
  { 'err' : string };
export type Result_5 = { 'ok' : Book } |
  { 'err' : string };
export type Result_6 = { 'ok' : Transfer } |
  { 'err' : string };
export type Result_7 = { 'ok' : { 'otp' : string, 'demo' : boolean } } |
  { 'err' : string };
export type Result_9 = { 'ok' : Notification } |
  { 'err' : string };
export interface ReturnTimelineEntry {
  'issueDate' : Timestamp,
  'requestId' : RequestId,
  'studentId' : UserId,
  'studentName' : string,
  'bookTitles' : Array<string>,
  'daysUntilReturn' : bigint,
  'phone' : string,
  'studentCourse' : string,
  'returnDate' : [] | [Timestamp],
  'returned' : boolean,
  'nextReservedStudent' : [] | [string],
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SmsProvider = { 'Fast2SMS' : null } |
  { 'Twilio' : null } |
  { 'MSG91' : null };
export interface SpecialRequest {
  'status' : BookDecisionStatus,
  'title' : string,
  'edition' : string,
  'publisher' : string,
  'procurementId' : [] | [ProcurementId],
  'author' : string,
  'expectedAvailabilityDate' : [] | [Timestamp],
  'reason' : [] | [string],
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface StudentProfileUpdate {
  'occupation' : string,
  'parentContact' : string,
  'birthDate' : string,
  'nativePlace' : string,
  'grandFatherName' : string,
  'educationSpecialization' : string,
  'surname' : string,
  'email' : string,
  'academicYear' : string,
  'middleName' : string,
  'currentLocation' : string,
  'course' : string,
  'courseName' : string,
  'officialSurname' : string,
  'educationLevel' : string,
  'college' : string,
  'occupationOther' : string,
  'firstName' : string,
}
export type Timestamp = bigint;
export interface Transfer {
  'id' : TransferId,
  'transferDate' : Timestamp,
  'challanId' : [] | [ChallanId],
  'bookId' : BookId,
  'toStudentId' : UserId,
  'fromStudentId' : UserId,
  'adminNotes' : [] | [string],
}
export type TransferId = string;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = string;
export interface UserPublic {
  'occupation' : string,
  'paymentStatus' : string,
  'studentId' : UserId,
  'parentContact' : string,
  'birthDate' : string,
  'nativePlace' : string,
  'grandFatherName' : string,
  'educationSpecialization' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'issuedBooksInfo' : Array<IssuedBookInfo>,
  'surname' : string,
  'frozenPhone' : boolean,
  'email' : string,
  'membershipStatus' : MembershipStatus,
  'academicYear' : string,
  'middleName' : string,
  'membershipStartDate' : Timestamp,
  'frozenAadhaar' : boolean,
  'paymentId' : string,
  'currentLocation' : string,
  'aadhaarNumber' : string,
  'phone' : string,
  'course' : string,
  'courseName' : string,
  'officialSurname' : string,
  'educationLevel' : string,
  'profileImageUrl' : string,
  'college' : string,
  'occupationOther' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaitingListAssignment {
  'assigned' : boolean,
  'nextStudentId' : [] | [UserId],
  'newRequestId' : [] | [RequestId],
  'nextStudentName' : [] | [string],
  'collectionOrderId' : [] | [CollectionOrderId],
}
export type WhatsAppProvider = { 'Meta' : null } |
  { 'Twilio' : null };
export type YearPromotionChoice = { 'ContinueNextYear' : null } |
  { 'ReturnBooks' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBook' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    Result_5
  >,
  'adminLogin' : ActorMethod<[string, string], AdminLoginResult>,
  'adminUpdateStudentProfile' : ActorMethod<
    [string, UserId, StudentProfileUpdate],
    Result_2
  >,
  'approveBook' : ActorMethod<[string, RequestId, BookId], Result_14>,
  'approveBookAndUpdateChallan' : ActorMethod<
    [
      string,
      RequestId,
      BookId,
      { 'RejectReservation' : null } |
        { 'Reject' : null } |
        { 'Accept' : null } |
        { 'AcceptReservation' : null },
      [] | [string],
      string,
    ],
    { 'ok' : { 'request' : BookRequest, 'challan' : Challan } } |
      { 'err' : string }
  >,
  'approveSpecialBook' : ActorMethod<[string, RequestId, bigint], Result_13>,
  'approveSpecialBookRequest' : ActorMethod<
    [string, RequestId, string],
    Result_27
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelReservation' : ActorMethod<[string, ReservationId], Result_4>,
  'checkBookAvailability' : ActorMethod<[BookId], Result_29>,
  'completeApproval' : ActorMethod<
    [string, RequestId, string, string, string, string],
    Result_26
  >,
  'completeProfileAndPay' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    Result_1
  >,
  'configureNotificationProviders' : ActorMethod<
    [string, ProviderConfig],
    Result_4
  >,
  'createAdminNotification' : ActorMethod<
    [string, string, string, string, [] | [string]],
    Result_9
  >,
  'createBookRequest' : ActorMethod<
    [string, Array<BookId>, Array<RequestedBookPublic>],
    Result_3
  >,
  'createBookReservation' : ActorMethod<
    [string, BookId, [] | [Timestamp]],
    Result_28
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createProcurementRequest' : ActorMethod<
    [
      string,
      string,
      [] | [BookId],
      [] | [string],
      [] | [string],
      [] | [string],
      ProcurementUrgency,
    ],
    Result_27
  >,
  'createReservation' : ActorMethod<
    [string, BookId, [] | [Timestamp]],
    Result_28
  >,
  'createStudentNotification' : ActorMethod<
    [string, UserId, NotificationEventType, string, string, [] | [string]],
    Result_9
  >,
  'createUrgentProcurementRequest' : ActorMethod<
    [
      string,
      string,
      [] | [BookId],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    Result_27
  >,
  'deleteBook' : ActorMethod<[string, BookId], Result_4>,
  'finalizeRequest' : ActorMethod<
    [string, RequestId, string, string, string],
    Result_26
  >,
  'generateChallanForRequest' : ActorMethod<
    [string, RequestId, string],
    { 'ok' : Challan } |
      { 'err' : string }
  >,
  'getAdminNotifications' : ActorMethod<[string], Array<Notification>>,
  'getAdminPendingCount' : ActorMethod<[string], bigint>,
  'getAdminReturnAlerts' : ActorMethod<
    [string],
    Array<
      {
        'bookTitle' : string,
        'requestId' : RequestId,
        'studentId' : UserId,
        'studentName' : string,
        'urgency' : string,
        'bookId' : BookId,
        'daysUntilReturn' : bigint,
        'returnDate' : [] | [Timestamp],
        'nextReservedStudent' : [] | [
          { 'studentId' : UserId, 'studentName' : string }
        ],
      }
    >
  >,
  'getAllBooks' : ActorMethod<[string], Array<Book>>,
  'getAllChallans' : ActorMethod<[string], Array<Challan>>,
  'getAllCollectionOrders' : ActorMethod<[string], Array<CollectionOrder>>,
  'getAllProcurements' : ActorMethod<[string], Array<ProcurementRequest>>,
  'getAllRequests' : ActorMethod<[string], Array<BookRequest>>,
  'getAllUsers' : ActorMethod<[string], Array<UserPublic>>,
  'getAnalyticsData' : ActorMethod<[string], AnalyticsData>,
  'getAuditLog' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [AuditAction],
      [] | [Timestamp],
      [] | [Timestamp],
    ],
    Result_25
  >,
  'getAuditLogs' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [AuditAction],
      [] | [Timestamp],
      [] | [Timestamp],
      bigint,
    ],
    Array<AuditEntry>
  >,
  'getAvailableDropOptions' : ActorMethod<
    [],
    { 'villages' : Array<string>, 'surnames' : Array<string> }
  >,
  'getBookById' : ActorMethod<[BookId], Result_5>,
  'getBookLifecycleFlow' : ActorMethod<
    [string],
    Array<
      {
        'bookTitle' : string,
        'bookId' : BookId,
        'currentHolder' : [] | [
          {
            'issueDate' : Timestamp,
            'userId' : UserId,
            'name' : string,
            'returnDate' : [] | [Timestamp],
          }
        ],
        'nextReservedStudent' : [] | [
          { 'reservationDate' : Timestamp, 'userId' : UserId, 'name' : string }
        ],
      }
    >
  >,
  'getBookRecommendations' : ActorMethod<[BookId], Array<Book>>,
  'getBooksReturningByDate' : ActorMethod<
    [string, bigint],
    Array<
      {
        'bookTitle' : string,
        'requestId' : RequestId,
        'studentId' : UserId,
        'studentName' : string,
        'bookId' : BookId,
        'daysUntilReturn' : bigint,
        'returnDate' : Timestamp,
        'nextReservedStudent' : [] | [
          { 'studentId' : UserId, 'studentName' : string }
        ],
      }
    >
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getChallan' : ActorMethod<[string, ChallanId], Result_24>,
  'getChallanById' : ActorMethod<[string, ChallanId], [] | [Challan]>,
  'getChallanPdfData' : ActorMethod<[string, ChallanId], Result_23>,
  'getCollectionOrder' : ActorMethod<[string, RequestId], Result_22>,
  'getCollectionOrderByNumber' : ActorMethod<[string, string], Result_22>,
  'getCollectionOrdersByAdmin' : ActorMethod<[string], Array<CollectionOrder>>,
  'getCollectionOrdersByStudent' : ActorMethod<
    [string, UserId],
    Array<CollectionOrder>
  >,
  'getCollectionQueue' : ActorMethod<[string], Array<CollectionEntry>>,
  'getCompletedForms' : ActorMethod<[string], Array<BookRequest>>,
  'getInventoryLifecycle' : ActorMethod<
    [string],
    Array<
      {
        'bookTitle' : string,
        'procurementRequests' : Array<ProcurementRequest>,
        'edition' : string,
        'publisher' : string,
        'waitingQueue' : Array<
          {
            'studentId' : UserId,
            'studentName' : string,
            'reservationDate' : Timestamp,
          }
        >,
        'bookId' : BookId,
        'availableCount' : bigint,
        'author' : string,
        'currentHolders' : Array<
          {
            'issueDate' : Timestamp,
            'studentId' : UserId,
            'studentName' : string,
            'expectedReturnDate' : Timestamp,
          }
        >,
        'totalQuantity' : bigint,
      }
    >
  >,
  'getManualBooksToPurchase' : ActorMethod<[string], Array<BookRequest>>,
  'getMyChallans' : ActorMethod<[string], Array<Challan>>,
  'getMyChallansList' : ActorMethod<[string], Array<Challan>>,
  'getMyIssuedBooks' : ActorMethod<[string], Array<BookRequest>>,
  'getMyNotifications' : ActorMethod<[string], Array<Notification>>,
  'getMyProcurements' : ActorMethod<[string], Array<ProcurementRequest>>,
  'getMyRequestOutcome' : ActorMethod<[string, RequestId], Result_21>,
  'getMyRequests' : ActorMethod<[string], Array<BookRequest>>,
  'getMyReservations' : ActorMethod<[string], Array<Reservation>>,
  'getNotificationConfig' : ActorMethod<[string], Result_20>,
  'getNotificationDeliveryStatus' : ActorMethod<
    [string, NotificationId],
    Result_19
  >,
  'getPaymentStatus' : ActorMethod<[string], Result_15>,
  'getPendingRequests' : ActorMethod<
    [string],
    Array<
      {
        'status' : string,
        'requestId' : RequestId,
        'studentId' : string,
        'studentName' : string,
        'phoneNumber' : string,
        'course' : string,
        'requestDate' : Timestamp,
        'totalBooksCount' : bigint,
      }
    >
  >,
  'getPendingRequestsFull' : ActorMethod<[string], Array<BookRequest>>,
  'getQrCodeData' : ActorMethod<[string, RequestId], string>,
  'getRequestById' : ActorMethod<[string, RequestId], Result_3>,
  'getRequestDetails' : ActorMethod<[string, RequestId], Result_18>,
  'getReservationsForBook' : ActorMethod<[BookId], Array<Reservation>>,
  'getReturnTimeline' : ActorMethod<[string], Array<ReturnTimelineEntry>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStudentByToken' : ActorMethod<[string], [] | [UserPublic]>,
  'getStudentChallans' : ActorMethod<[string, UserId], Array<Challan>>,
  'getStudentProfile' : ActorMethod<[UserId], [] | [UserPublic]>,
  'getStudentQrUrl' : ActorMethod<[UserId], string>,
  'getTransferHistory' : ActorMethod<[string], Array<Transfer>>,
  'getTransfersForBook' : ActorMethod<[BookId], Array<Transfer>>,
  'getUnreadCount' : ActorMethod<[string], bigint>,
  'importBooksFromCsv' : ActorMethod<[string, Array<BookCsvRow>], Result_17>,
  'initiateYearPromotion' : ActorMethod<[string, string], bigint>,
  'isAadhaarAvailable' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmailAvailable' : ActorMethod<[string], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[string], Result_4>,
  'markBookCollected' : ActorMethod<[string, RequestId, BookId], Result_4>,
  'markBookReturned' : ActorMethod<[string, RequestId], Result_3>,
  'markNotificationRead' : ActorMethod<[string, NotificationId], Result_4>,
  'processYearPromotion' : ActorMethod<
    [string, YearPromotionChoice],
    Result_16
  >,
  'recordPayment' : ActorMethod<[string, string, bigint], Result_15>,
  'rejectBook' : ActorMethod<
    [string, RequestId, BookId, [] | [string]],
    Result_14
  >,
  'rejectSpecialBook' : ActorMethod<
    [string, RequestId, bigint, [] | [string]],
    Result_13
  >,
  'rejectSpecialBookRequest' : ActorMethod<
    [string, RequestId, string, [] | [string]],
    Result_4
  >,
  'reserveBook' : ActorMethod<
    [string, RequestId, BookId, [] | [Timestamp]],
    Result_12
  >,
  'searchBooks' : ActorMethod<[string, string], Array<Book>>,
  'searchInventory' : ActorMethod<
    [string, [] | [string], [] | [string]],
    Array<Book>
  >,
  'searchRequests' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    Array<BookRequest>
  >,
  'searchStudents' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    Array<UserPublic>
  >,
  'seedBooks' : ActorMethod<[string, Array<BookInput>], Result_11>,
  'sendChallanEmail' : ActorMethod<
    [string, ChallanId],
    { 'ok' : EmailSendResult } |
      { 'err' : string }
  >,
  'sendEmailNotification' : ActorMethod<
    [string, string, string, string, [] | [string]],
    Result_10
  >,
  'sendLifecycleEmail' : ActorMethod<
    [
      UserId,
      NotificationEventType,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    Result_10
  >,
  'sendMultiChannelNotification' : ActorMethod<
    [
      string,
      UserId,
      string,
      [] | [string],
      [] | [string],
      Array<NotificationChannel>,
    ],
    Result_9
  >,
  'sendOtp' : ActorMethod<[string, string], Result_7>,
  'sendOtpWithEmail' : ActorMethod<[string, string, string], Result_7>,
  'setAdminCredentials' : ActorMethod<[string, string, string], Result_4>,
  'setReturnDate' : ActorMethod<[string, RequestId, Timestamp], Result_4>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'studentLogout' : ActorMethod<[string], undefined>,
  'studentSignupAndPay' : ActorMethod<
    [string, string, string, string, string, string, string],
    Result_1
  >,
  'transferBook' : ActorMethod<
    [string, UserId, UserId, BookId, [] | [string]],
    Result_6
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerReturnReminders' : ActorMethod<[string], bigint>,
  'updateBook' : ActorMethod<
    [string, BookId, string, string, string, string, string, bigint, bigint],
    Result_5
  >,
  'updateBookApproval' : ActorMethod<
    [
      string,
      RequestId,
      BookId,
      { 'RejectReservation' : null } |
        { 'Reject' : null } |
        { 'Accept' : null } |
        { 'AcceptReservation' : null },
      [] | [string],
    ],
    Result_3
  >,
  'updateIssuedBookStatus' : ActorMethod<
    [string, RequestId, boolean],
    Result_4
  >,
  'updateManualBookStatus' : ActorMethod<
    [string, RequestId, string, BookDecisionStatus],
    Result_4
  >,
  'updateProcurementStatus' : ActorMethod<
    [string, ProcurementId, ProcurementStatus],
    Result_4
  >,
  'updateRequestStatus' : ActorMethod<[string, RequestId, string], Result_3>,
  'updateStudent' : ActorMethod<
    [
      string,
      UserId,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    Result_2
  >,
  'updateStudentProfile' : ActorMethod<
    [string, StudentProfileUpdate],
    Result_2
  >,
  'verifyOtpAndLogin' : ActorMethod<
    [string, string, string, string, string, string],
    Result_1
  >,
  'verifyOtpWithEmail' : ActorMethod<
    [string, string, string, string],
    Result_1
  >,
  'verifyStudentToken' : ActorMethod<[string], [] | [UserPublic]>,
  'waitingListAutoAssign' : ActorMethod<[string, BookId, RequestId], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];