/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Text;
export const BookId = IDL.Text;
export const Book = IDL.Record({
  'title' : IDL.Text,
  'isDeleted' : IDL.Bool,
  'edition' : IDL.Text,
  'availableQuantity' : IDL.Nat,
  'publisher' : IDL.Text,
  'createdAt' : Timestamp,
  'waitingQueue' : IDL.Vec(UserId),
  'isAvailable' : IDL.Bool,
  'bookId' : BookId,
  'availableCount' : IDL.Nat,
  'author' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'currentHolders' : IDL.Vec(UserId),
  'totalQuantity' : IDL.Nat,
});
export const Result_5 = IDL.Variant({ 'ok' : Book, 'err' : IDL.Text });
export const AdminLoginResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : IDL.Text, 'expiresAt' : Timestamp }),
  'err' : IDL.Text,
});
export const StudentProfileUpdate = IDL.Record({
  'occupation' : IDL.Text,
  'parentContact' : IDL.Text,
  'birthDate' : IDL.Text,
  'nativePlace' : IDL.Text,
  'grandFatherName' : IDL.Text,
  'educationSpecialization' : IDL.Text,
  'surname' : IDL.Text,
  'email' : IDL.Text,
  'academicYear' : IDL.Text,
  'middleName' : IDL.Text,
  'currentLocation' : IDL.Text,
  'course' : IDL.Text,
  'courseName' : IDL.Text,
  'officialSurname' : IDL.Text,
  'educationLevel' : IDL.Text,
  'college' : IDL.Text,
  'occupationOther' : IDL.Text,
  'firstName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'student' : IDL.Null,
});
export const RequestId = IDL.Text;
export const IssuedBookInfo = IDL.Record({
  'bookTitle' : IDL.Text,
  'issueDate' : Timestamp,
  'status' : IDL.Text,
  'requestId' : RequestId,
  'studentName' : IDL.Text,
  'userId' : UserId,
  'bookId' : BookId,
  'bookIds' : IDL.Vec(BookId),
  'expectedReturnDate' : Timestamp,
  'returnDate' : IDL.Opt(Timestamp),
  'returned' : IDL.Bool,
});
export const MembershipStatus = IDL.Variant({
  'PAID' : IDL.Null,
  'NOT_PAID' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'occupation' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'studentId' : UserId,
  'parentContact' : IDL.Text,
  'birthDate' : IDL.Text,
  'nativePlace' : IDL.Text,
  'grandFatherName' : IDL.Text,
  'educationSpecialization' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'issuedBooksInfo' : IDL.Vec(IssuedBookInfo),
  'surname' : IDL.Text,
  'frozenPhone' : IDL.Bool,
  'email' : IDL.Text,
  'membershipStatus' : MembershipStatus,
  'academicYear' : IDL.Text,
  'middleName' : IDL.Text,
  'membershipStartDate' : Timestamp,
  'frozenAadhaar' : IDL.Bool,
  'paymentId' : IDL.Text,
  'currentLocation' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'phone' : IDL.Text,
  'course' : IDL.Text,
  'courseName' : IDL.Text,
  'officialSurname' : IDL.Text,
  'educationLevel' : IDL.Text,
  'profileImageUrl' : IDL.Text,
  'college' : IDL.Text,
  'occupationOther' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text });
export const BookDecisionStatus = IDL.Variant({
  'Arrived' : IDL.Null,
  'Reserved' : IDL.Null,
  'Ordered' : IDL.Null,
  'Purchased' : IDL.Null,
  'SpecialOrder' : IDL.Null,
  'ReadyForCollection' : IDL.Null,
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Issued' : IDL.Null,
  'Returned' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ProcurementId = IDL.Text;
export const BookDecision = IDL.Record({
  'decision' : BookDecisionStatus,
  'bookNumber' : IDL.Text,
  'bookName' : IDL.Text,
  'edition' : IDL.Text,
  'subject' : IDL.Text,
  'publisher' : IDL.Text,
  'procurementId' : IDL.Opt(ProcurementId),
  'currentHolderStudentId' : IDL.Opt(IDL.Text),
  'bookId' : BookId,
  'queuePosition' : IDL.Opt(IDL.Nat),
  'author' : IDL.Text,
  'procurementCreated' : IDL.Bool,
  'expectedReturnDate' : IDL.Opt(Timestamp),
  'currentHolder' : IDL.Opt(IDL.Text),
  'inventoryId' : IDL.Text,
  'reason' : IDL.Opt(IDL.Text),
});
export const Result_14 = IDL.Variant({ 'ok' : BookDecision, 'err' : IDL.Text });
export const ChallanId = IDL.Text;
export const SpecialRequest = IDL.Record({
  'status' : BookDecisionStatus,
  'title' : IDL.Text,
  'edition' : IDL.Text,
  'publisher' : IDL.Text,
  'procurementId' : IDL.Opt(ProcurementId),
  'author' : IDL.Text,
  'expectedAvailabilityDate' : IDL.Opt(Timestamp),
  'reason' : IDL.Opt(IDL.Text),
});
export const RequestedBookPublic = IDL.Record({
  'title' : IDL.Text,
  'edition' : IDL.Text,
  'publisher' : IDL.Text,
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const BookRequest = IDL.Record({
  'issueDate' : IDL.Opt(Timestamp),
  'status' : IDL.Text,
  'bookApprovals' : IDL.Vec(IDL.Tuple(BookId, IDL.Text)),
  'studentEmail' : IDL.Text,
  'studentAadhaar' : IDL.Text,
  'requestId' : RequestId,
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'studentYear' : IDL.Text,
  'challanId' : IDL.Opt(ChallanId),
  'requestNotes' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'specialRequests' : IDL.Vec(SpecialRequest),
  'createdAt' : Timestamp,
  'requestedBooks' : IDL.Vec(RequestedBookPublic),
  'studentPhone' : IDL.Text,
  'requestNumber' : IDL.Text,
  'collectionOrderId' : IDL.Opt(IDL.Text),
  'adminName' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'bookDecisions' : IDL.Vec(BookDecision),
  'adminId' : IDL.Opt(IDL.Text),
  'studentCourse' : IDL.Text,
  'challanData' : IDL.Text,
  'returnDate' : IDL.Opt(Timestamp),
  'returned' : IDL.Bool,
  'selectedBookIds' : IDL.Vec(BookId),
  'collectionDate' : IDL.Text,
  'collectionLocation' : IDL.Text,
  'collectionTime' : IDL.Text,
});
export const ProcurementStatus = IDL.Variant({
  'Procured' : IDL.Null,
  'Ordered' : IDL.Null,
  'ReadyForCollection' : IDL.Null,
  'Approved' : IDL.Null,
  'Issued' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Returned' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ProcurementUrgency = IDL.Variant({
  'Required' : IDL.Null,
  'Optional' : IDL.Null,
});
export const ProcurementRequest = IDL.Record({
  'id' : ProcurementId,
  'bookTitle' : IDL.Text,
  'status' : ProcurementStatus,
  'studentId' : UserId,
  'edition' : IDL.Opt(IDL.Text),
  'urgency' : ProcurementUrgency,
  'publisher' : IDL.Opt(IDL.Text),
  'bookId' : IDL.Opt(BookId),
  'author' : IDL.Opt(IDL.Text),
  'requestDate' : Timestamp,
});
export const ReservationId = IDL.Text;
export const ReservationStatus = IDL.Variant({
  'Waiting' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Fulfilled' : IDL.Null,
});
export const Reservation = IDL.Record({
  'id' : ReservationId,
  'status' : ReservationStatus,
  'studentId' : UserId,
  'bookId' : BookId,
  'expectedAvailabilityDate' : IDL.Opt(Timestamp),
  'requestDate' : Timestamp,
});
export const BookAvailabilityDate = IDL.Record({
  'bookTitle' : IDL.Text,
  'bookId' : BookId,
  'expectedDate' : Timestamp,
});
export const ChallanBookEntry = IDL.Record({
  'status' : BookDecisionStatus,
  'title' : IDL.Text,
  'bookNumber' : IDL.Text,
  'edition' : IDL.Text,
  'subject' : IDL.Text,
  'publisher' : IDL.Text,
  'currentHolderStudentId' : IDL.Opt(IDL.Text),
  'bookId' : BookId,
  'queuePosition' : IDL.Opt(IDL.Nat),
  'author' : IDL.Text,
  'expectedAvailabilityDate' : IDL.Opt(Timestamp),
  'expectedReturnDate' : IDL.Opt(Timestamp),
  'currentHolder' : IDL.Opt(IDL.Text),
  'reason' : IDL.Opt(IDL.Text),
});
export const Challan = IDL.Record({
  'challanNumber' : IDL.Text,
  'trackingEvents' : IDL.Vec(IDL.Text),
  'status' : IDL.Text,
  'studentEmail' : IDL.Text,
  'signatureAdmin' : IDL.Opt(IDL.Text),
  'signatureStudent' : IDL.Opt(IDL.Text),
  'procurementRequests' : IDL.Vec(ProcurementRequest),
  'studentId' : UserId,
  'qrCodeData' : IDL.Opt(IDL.Text),
  'studentName' : IDL.Text,
  'studentYear' : IDL.Text,
  'challanId' : ChallanId,
  'reservations' : IDL.Vec(Reservation),
  'trackedBookIds' : IDL.Vec(BookId),
  'generatedAt' : Timestamp,
  'specialRequests' : IDL.Vec(SpecialRequest),
  'createdAt' : Timestamp,
  'availabilityDates' : IDL.Vec(BookAvailabilityDate),
  'studentPhone' : IDL.Text,
  'requestNumber' : RequestId,
  'orderedBooks' : IDL.Vec(ChallanBookEntry),
  'rejectedBooks' : IDL.Vec(ChallanBookEntry),
  'returnedBooks' : IDL.Vec(ChallanBookEntry),
  'arrivedBooks' : IDL.Vec(ChallanBookEntry),
  'adminName' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'bookDecisions' : IDL.Vec(BookDecision),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'qrCodeUrl' : IDL.Text,
  'approvedBooks' : IDL.Vec(ChallanBookEntry),
  'reservedBooks' : IDL.Vec(ChallanBookEntry),
  'manualBooks' : IDL.Vec(ChallanBookEntry),
  'collectionOrderNumber' : IDL.Text,
  'issuedBookIds' : IDL.Vec(BookId),
  'studentCourse' : IDL.Text,
  'issuedBooks' : IDL.Vec(ChallanBookEntry),
  'readyForCollectionBooks' : IDL.Vec(ChallanBookEntry),
  'expectedDates' : IDL.Vec(BookAvailabilityDate),
  'collectionDate' : IDL.Text,
  'collectionTime' : IDL.Text,
});
export const Result_13 = IDL.Variant({
  'ok' : SpecialRequest,
  'err' : IDL.Text,
});
export const Result_27 = IDL.Variant({
  'ok' : ProcurementRequest,
  'err' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Result_29 = IDL.Variant({
  'ok' : IDL.Record({
    'waitingCount' : IDL.Nat,
    'available' : IDL.Bool,
    'expectedReturnDate' : IDL.Opt(Timestamp),
    'daysUntilReturn' : IDL.Opt(IDL.Int),
  }),
  'err' : IDL.Text,
});
export const CollectionOrder = IDL.Record({
  'status' : IDL.Variant({
    'Collected' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  }),
  'studentEmail' : IDL.Text,
  'requestId' : RequestId,
  'studentId' : UserId,
  'studentName' : IDL.Text,
  'studentYear' : IDL.Text,
  'challanId' : IDL.Opt(ChallanId),
  'generatedAt' : Timestamp,
  'specialRequests' : IDL.Vec(SpecialRequest),
  'studentPhone' : IDL.Text,
  'orderedBooks' : IDL.Vec(BookDecision),
  'rejectedBooks' : IDL.Vec(BookDecision),
  'orderId' : IDL.Text,
  'returnedBooks' : IDL.Vec(BookDecision),
  'arrivedBooks' : IDL.Vec(BookDecision),
  'adminName' : IDL.Text,
  'bookDecisions' : IDL.Vec(BookDecision),
  'approvedBooks' : IDL.Vec(BookDecision),
  'reservedBooks' : IDL.Vec(BookDecision),
  'studentCourse' : IDL.Text,
  'issuedBooks' : IDL.Vec(BookDecision),
  'orderNumber' : IDL.Text,
  'readyForCollectionBooks' : IDL.Vec(BookDecision),
  'collectionDate' : IDL.Text,
  'collectionLocation' : IDL.Text,
  'collectionTime' : IDL.Text,
});
export const CompleteApprovalResult = IDL.Record({
  'collectionOrder' : CollectionOrder,
  'request' : BookRequest,
  'challan' : Challan,
});
export const Result_26 = IDL.Variant({
  'ok' : CompleteApprovalResult,
  'err' : IDL.Text,
});
export const AuthResult = IDL.Record({
  'token' : IDL.Text,
  'userId' : IDL.Text,
  'user' : UserPublic,
});
export const Result_1 = IDL.Variant({ 'ok' : AuthResult, 'err' : IDL.Text });
export const WhatsAppProvider = IDL.Variant({
  'Meta' : IDL.Null,
  'Twilio' : IDL.Null,
});
export const SmsProvider = IDL.Variant({
  'Fast2SMS' : IDL.Null,
  'Twilio' : IDL.Null,
  'MSG91' : IDL.Null,
});
export const ProviderConfig = IDL.Record({
  'whatsAppApiKey' : IDL.Opt(IDL.Text),
  'whatsAppProvider' : IDL.Opt(WhatsAppProvider),
  'smsSenderId' : IDL.Opt(IDL.Text),
  'smsProvider' : IDL.Opt(SmsProvider),
  'smsApiKey' : IDL.Opt(IDL.Text),
  'whatsAppSenderId' : IDL.Opt(IDL.Text),
});
export const NotificationId = IDL.Text;
export const NotificationKind = IDL.Variant({
  'BookReadyForCollection' : IDL.Null,
  'ReturnAlert' : IDL.Null,
  'CourseCompletion' : IDL.Null,
  'PaymentSuccess' : IDL.Null,
  'QueueUpdate' : IDL.Null,
  'RegistrationSuccess' : IDL.Null,
  'ChallanGenerated' : IDL.Null,
  'General' : IDL.Null,
  'BookReserved' : IDL.Null,
  'ProcurementNeeded' : IDL.Null,
  'DueDateReminder' : IDL.Null,
  'BookApproved' : IDL.Null,
  'ReservationFulfilled' : IDL.Null,
  'BookAvailable' : IDL.Null,
  'YearPromotion' : IDL.Null,
  'BookTransferred' : IDL.Null,
  'ReturnReminder' : IDL.Null,
  'BookRejected' : IDL.Null,
});
export const DeliveryStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Demo' : IDL.Null,
  'Sent' : IDL.Null,
  'Pending' : IDL.Null,
});
export const NotificationChannel = IDL.Variant({
  'SMS' : IDL.Null,
  'Email' : IDL.Null,
  'WhatsApp' : IDL.Null,
  'Website' : IDL.Null,
});
export const NotificationDeliveryStatus = IDL.Record({
  'status' : DeliveryStatus,
  'sentAt' : IDL.Opt(Timestamp),
  'error' : IDL.Opt(IDL.Text),
  'channel' : NotificationChannel,
});
export const NotificationBookOutcome = IDL.Record({
  'status' : BookDecisionStatus,
  'bookNumber' : IDL.Text,
  'bookName' : IDL.Text,
  'edition' : IDL.Text,
  'author' : IDL.Text,
  'expectedAvailabilityDate' : IDL.Opt(Timestamp),
  'expectedReturnDate' : IDL.Opt(Timestamp),
  'currentHolder' : IDL.Opt(IDL.Text),
  'reason' : IDL.Opt(IDL.Text),
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'actionUrl' : IDL.Opt(IDL.Text),
  'userId' : IDL.Text,
  'kind' : NotificationKind,
  'deliveryStatus' : IDL.Vec(NotificationDeliveryStatus),
  'isRead' : IDL.Bool,
  'challanUrl' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'emailSent' : IDL.Bool,
  'bookOutcomes' : IDL.Vec(NotificationBookOutcome),
  'collectionDate' : IDL.Opt(IDL.Text),
  'collectionLocation' : IDL.Opt(IDL.Text),
  'collectionTime' : IDL.Opt(IDL.Text),
  'eventType' : IDL.Opt(IDL.Text),
  'readAt' : IDL.Opt(Timestamp),
});
export const Result_9 = IDL.Variant({ 'ok' : Notification, 'err' : IDL.Text });
export const Result_3 = IDL.Variant({ 'ok' : BookRequest, 'err' : IDL.Text });
export const Result_28 = IDL.Variant({ 'ok' : Reservation, 'err' : IDL.Text });
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const NotificationEventType = IDL.Text;
export const AnalyticsData = IDL.Record({
  'returnedRequests' : IDL.Nat,
  'requestsOverTime' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'waitingListCount' : IDL.Nat,
  'rejectedRequests' : IDL.Nat,
  'activeStudents' : IDL.Nat,
  'totalProcurements' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'totalReservations' : IDL.Nat,
  'booksIssued' : IDL.Nat,
  'pendingRequests' : IDL.Nat,
  'approvedRequests' : IDL.Nat,
  'booksAvailable' : IDL.Nat,
  'lowStockBooks' : IDL.Nat,
  'reservedBooks' : IDL.Nat,
  'totalBooks' : IDL.Nat,
  'booksOverdue' : IDL.Nat,
  'booksByCategory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'dueReturns' : IDL.Nat,
});
export const AuditAction = IDL.Variant({
  'BookRequest' : IDL.Null,
  'RequestOpened' : IDL.Null,
  'ChallanGenerated' : IDL.Null,
  'BookIssue' : IDL.Null,
  'ProfileUpdate' : IDL.Null,
  'NotificationSent' : IDL.Null,
  'BookReturn' : IDL.Null,
  'ReservationCreation' : IDL.Null,
  'BookReserved' : IDL.Null,
  'RequestFinalized' : IDL.Null,
  'CollectionOrderGenerated' : IDL.Null,
  'StudentRegistration' : IDL.Null,
  'BookRejection' : IDL.Null,
  'BookApproval' : IDL.Null,
  'BookCollected' : IDL.Null,
  'AdminChange' : IDL.Null,
  'CollectionDateAssigned' : IDL.Null,
});
export const ActorType = IDL.Variant({
  'Student' : IDL.Null,
  'Admin' : IDL.Null,
});
export const AuditBookDecision = IDL.Record({
  'status' : BookDecisionStatus,
  'bookNumber' : IDL.Text,
  'bookName' : IDL.Text,
  'author' : IDL.Text,
  'reason' : IDL.Opt(IDL.Text),
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : AuditAction,
  'actorName' : IDL.Opt(IDL.Text),
  'actorType' : ActorType,
  'studentName' : IDL.Opt(IDL.Text),
  'resourceId' : IDL.Text,
  'requestNumber' : IDL.Opt(IDL.Text),
  'actorId' : IDL.Text,
  'adminName' : IDL.Opt(IDL.Text),
  'resourceType' : IDL.Opt(IDL.Text),
  'bookDecisions' : IDL.Vec(AuditBookDecision),
  'timestamp' : Timestamp,
  'details' : IDL.Opt(IDL.Text),
  'userAgent' : IDL.Opt(IDL.Text),
  'ipAddress' : IDL.Opt(IDL.Text),
});
export const Result_25 = IDL.Variant({
  'ok' : IDL.Vec(AuditEntry),
  'err' : IDL.Text,
});
export const Result_24 = IDL.Variant({ 'ok' : Challan, 'err' : IDL.Text });
export const ChallanPdfData = IDL.Record({
  'adminSignaturePlaceholder' : IDL.Text,
  'studentSignaturePlaceholder' : IDL.Text,
  'qrCodeUrl' : IDL.Text,
  'collectionOrderNumber' : IDL.Text,
  'challan' : Challan,
  'collectionDate' : IDL.Text,
  'collectionLocation' : IDL.Text,
  'collectionTime' : IDL.Text,
});
export const Result_23 = IDL.Variant({
  'ok' : ChallanPdfData,
  'err' : IDL.Text,
});
export const Result_22 = IDL.Variant({
  'ok' : CollectionOrder,
  'err' : IDL.Text,
});
export const CollectionEntry = IDL.Record({
  'bookTitle' : IDL.Text,
  'requestId' : RequestId,
  'studentId' : UserId,
  'studentName' : IDL.Text,
  'bookId' : BookId,
  'collectionDeadline' : Timestamp,
  'approvalDate' : Timestamp,
  'entryId' : IDL.Text,
  'collected' : IDL.Bool,
});
export const RequestOutcome = IDL.Record({
  'requestId' : RequestId,
  'challanId' : IDL.Opt(ChallanId),
  'requestNumber' : IDL.Text,
  'rejectedBooks' : IDL.Vec(BookDecision),
  'collectionOrderId' : IDL.Opt(IDL.Text),
  'approvedBooks' : IDL.Vec(BookDecision),
  'reservedBooks' : IDL.Vec(BookDecision),
  'overallStatus' : IDL.Text,
  'collectionDate' : IDL.Text,
  'collectionLocation' : IDL.Text,
  'collectionTime' : IDL.Text,
});
export const Result_21 = IDL.Variant({
  'ok' : RequestOutcome,
  'err' : IDL.Text,
});
export const Result_20 = IDL.Variant({
  'ok' : IDL.Record({
    'demoMode' : IDL.Bool,
    'whatsAppConfigured' : IDL.Bool,
    'smsConfigured' : IDL.Bool,
  }),
  'err' : IDL.Text,
});
export const Result_19 = IDL.Variant({
  'ok' : IDL.Record({
    'pending' : IDL.Nat,
    'demo' : IDL.Nat,
    'sent' : IDL.Nat,
    'failed' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const PaymentId = IDL.Text;
export const Payment = IDL.Record({
  'status' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'paymentId' : PaymentId,
  'stripePaymentId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Result_15 = IDL.Variant({ 'ok' : Payment, 'err' : IDL.Text });
export const BookDetailView = IDL.Record({
  'title' : IDL.Text,
  'decision' : IDL.Opt(BookDecision),
  'bookNumber' : IDL.Text,
  'edition' : IDL.Text,
  'subject' : IDL.Text,
  'publisher' : IDL.Text,
  'queueLength' : IDL.Nat,
  'bookId' : BookId,
  'author' : IDL.Text,
  'expectedReturnDate' : IDL.Opt(Timestamp),
  'currentHolder' : IDL.Opt(IDL.Text),
  'inventoryId' : IDL.Text,
  'availabilityStatus' : IDL.Text,
});
export const RequestDetails = IDL.Record({
  'request' : BookRequest,
  'specialRequests' : IDL.Vec(SpecialRequest),
  'student' : UserPublic,
  'books' : IDL.Vec(BookDetailView),
});
export const Result_18 = IDL.Variant({
  'ok' : RequestDetails,
  'err' : IDL.Text,
});
export const ReturnTimelineEntry = IDL.Record({
  'issueDate' : Timestamp,
  'requestId' : RequestId,
  'studentId' : UserId,
  'studentName' : IDL.Text,
  'bookTitles' : IDL.Vec(IDL.Text),
  'daysUntilReturn' : IDL.Int,
  'phone' : IDL.Text,
  'studentCourse' : IDL.Text,
  'returnDate' : IDL.Opt(Timestamp),
  'returned' : IDL.Bool,
  'nextReservedStudent' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TransferId = IDL.Text;
export const Transfer = IDL.Record({
  'id' : TransferId,
  'transferDate' : Timestamp,
  'challanId' : IDL.Opt(ChallanId),
  'bookId' : BookId,
  'toStudentId' : UserId,
  'fromStudentId' : UserId,
  'adminNotes' : IDL.Opt(IDL.Text),
});
export const BookCsvRow = IDL.Record({
  'title' : IDL.Text,
  'availableCopies' : IDL.Nat,
  'edition' : IDL.Text,
  'publisher' : IDL.Text,
  'author' : IDL.Text,
  'totalCopies' : IDL.Nat,
  'category' : IDL.Text,
});
export const CsvImportResult = IDL.Record({
  'skipped' : IDL.Nat,
  'errors' : IDL.Vec(IDL.Text),
  'processed' : IDL.Nat,
});
export const Result_17 = IDL.Variant({
  'ok' : CsvImportResult,
  'err' : IDL.Text,
});
export const YearPromotionChoice = IDL.Variant({
  'ContinueNextYear' : IDL.Null,
  'ReturnBooks' : IDL.Null,
});
export const Result_16 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Result_12 = IDL.Variant({
  'ok' : IDL.Record({ 'reservation' : Reservation, 'queuePosition' : IDL.Nat }),
  'err' : IDL.Text,
});
export const BookInput = IDL.Record({
  'title' : IDL.Text,
  'edition' : IDL.Text,
  'publisher' : IDL.Text,
  'author' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const Result_11 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const EmailSendResult = IDL.Record({
  'messageId' : IDL.Opt(IDL.Text),
  'sentAt' : Timestamp,
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const Result_10 = IDL.Variant({
  'ok' : EmailSendResult,
  'err' : IDL.Text,
});
export const Result_7 = IDL.Variant({
  'ok' : IDL.Record({ 'otp' : IDL.Text, 'demo' : IDL.Bool }),
  'err' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const Result_6 = IDL.Variant({ 'ok' : Transfer, 'err' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const CollectionOrderId = IDL.Text;
export const WaitingListAssignment = IDL.Record({
  'assigned' : IDL.Bool,
  'nextStudentId' : IDL.Opt(UserId),
  'newRequestId' : IDL.Opt(RequestId),
  'nextStudentName' : IDL.Opt(IDL.Text),
  'collectionOrderId' : IDL.Opt(CollectionOrderId),
});
export const Result = IDL.Variant({
  'ok' : WaitingListAssignment,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Result_5],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [AdminLoginResult], []),
  'adminUpdateStudentProfile' : IDL.Func(
      [IDL.Text, UserId, StudentProfileUpdate],
      [Result_2],
      [],
    ),
  'approveBook' : IDL.Func([IDL.Text, RequestId, BookId], [Result_14], []),
  'approveBookAndUpdateChallan' : IDL.Func(
      [
        IDL.Text,
        RequestId,
        BookId,
        IDL.Variant({
          'RejectReservation' : IDL.Null,
          'Reject' : IDL.Null,
          'Accept' : IDL.Null,
          'AcceptReservation' : IDL.Null,
        }),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'request' : BookRequest, 'challan' : Challan }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'approveSpecialBook' : IDL.Func(
      [IDL.Text, RequestId, IDL.Nat],
      [Result_13],
      [],
    ),
  'approveSpecialBookRequest' : IDL.Func(
      [IDL.Text, RequestId, IDL.Text],
      [Result_27],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelReservation' : IDL.Func([IDL.Text, ReservationId], [Result_4], []),
  'checkBookAvailability' : IDL.Func([BookId], [Result_29], ['query']),
  'completeApproval' : IDL.Func(
      [IDL.Text, RequestId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_26],
      [],
    ),
  'completeProfileAndPay' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Result_1],
      [],
    ),
  'configureNotificationProviders' : IDL.Func(
      [IDL.Text, ProviderConfig],
      [Result_4],
      [],
    ),
  'createAdminNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result_9],
      [],
    ),
  'createBookRequest' : IDL.Func(
      [IDL.Text, IDL.Vec(BookId), IDL.Vec(RequestedBookPublic)],
      [Result_3],
      [],
    ),
  'createBookReservation' : IDL.Func(
      [IDL.Text, BookId, IDL.Opt(Timestamp)],
      [Result_28],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createProcurementRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(BookId),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        ProcurementUrgency,
      ],
      [Result_27],
      [],
    ),
  'createReservation' : IDL.Func(
      [IDL.Text, BookId, IDL.Opt(Timestamp)],
      [Result_28],
      [],
    ),
  'createStudentNotification' : IDL.Func(
      [
        IDL.Text,
        UserId,
        NotificationEventType,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [Result_9],
      [],
    ),
  'createUrgentProcurementRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(BookId),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Result_27],
      [],
    ),
  'deleteBook' : IDL.Func([IDL.Text, BookId], [Result_4], []),
  'finalizeRequest' : IDL.Func(
      [IDL.Text, RequestId, IDL.Text, IDL.Text, IDL.Text],
      [Result_26],
      [],
    ),
  'generateChallanForRequest' : IDL.Func(
      [IDL.Text, RequestId, IDL.Text],
      [IDL.Variant({ 'ok' : Challan, 'err' : IDL.Text })],
      [],
    ),
  'getAdminNotifications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getAdminPendingCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getAdminReturnAlerts' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'bookTitle' : IDL.Text,
            'requestId' : RequestId,
            'studentId' : UserId,
            'studentName' : IDL.Text,
            'urgency' : IDL.Text,
            'bookId' : BookId,
            'daysUntilReturn' : IDL.Int,
            'returnDate' : IDL.Opt(Timestamp),
            'nextReservedStudent' : IDL.Opt(
              IDL.Record({ 'studentId' : UserId, 'studentName' : IDL.Text })
            ),
          })
        ),
      ],
      ['query'],
    ),
  'getAllBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'getAllChallans' : IDL.Func([IDL.Text], [IDL.Vec(Challan)], ['query']),
  'getAllCollectionOrders' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CollectionOrder)],
      ['query'],
    ),
  'getAllProcurements' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProcurementRequest)],
      ['query'],
    ),
  'getAllRequests' : IDL.Func([IDL.Text], [IDL.Vec(BookRequest)], ['query']),
  'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserPublic)], ['query']),
  'getAnalyticsData' : IDL.Func([IDL.Text], [AnalyticsData], ['query']),
  'getAuditLog' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(AuditAction),
        IDL.Opt(Timestamp),
        IDL.Opt(Timestamp),
      ],
      [Result_25],
      ['query'],
    ),
  'getAuditLogs' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(AuditAction),
        IDL.Opt(Timestamp),
        IDL.Opt(Timestamp),
        IDL.Nat,
      ],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'getAvailableDropOptions' : IDL.Func(
      [],
      [
        IDL.Record({
          'villages' : IDL.Vec(IDL.Text),
          'surnames' : IDL.Vec(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getBookById' : IDL.Func([BookId], [Result_5], ['query']),
  'getBookLifecycleFlow' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'bookTitle' : IDL.Text,
            'bookId' : BookId,
            'currentHolder' : IDL.Opt(
              IDL.Record({
                'issueDate' : Timestamp,
                'userId' : UserId,
                'name' : IDL.Text,
                'returnDate' : IDL.Opt(Timestamp),
              })
            ),
            'nextReservedStudent' : IDL.Opt(
              IDL.Record({
                'reservationDate' : Timestamp,
                'userId' : UserId,
                'name' : IDL.Text,
              })
            ),
          })
        ),
      ],
      ['query'],
    ),
  'getBookRecommendations' : IDL.Func([BookId], [IDL.Vec(Book)], ['query']),
  'getBooksReturningByDate' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'bookTitle' : IDL.Text,
            'requestId' : RequestId,
            'studentId' : UserId,
            'studentName' : IDL.Text,
            'bookId' : BookId,
            'daysUntilReturn' : IDL.Int,
            'returnDate' : Timestamp,
            'nextReservedStudent' : IDL.Opt(
              IDL.Record({ 'studentId' : UserId, 'studentName' : IDL.Text })
            ),
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getChallan' : IDL.Func([IDL.Text, ChallanId], [Result_24], ['query']),
  'getChallanById' : IDL.Func(
      [IDL.Text, ChallanId],
      [IDL.Opt(Challan)],
      ['query'],
    ),
  'getChallanPdfData' : IDL.Func([IDL.Text, ChallanId], [Result_23], ['query']),
  'getCollectionOrder' : IDL.Func(
      [IDL.Text, RequestId],
      [Result_22],
      ['query'],
    ),
  'getCollectionOrderByNumber' : IDL.Func(
      [IDL.Text, IDL.Text],
      [Result_22],
      ['query'],
    ),
  'getCollectionOrdersByAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CollectionOrder)],
      ['query'],
    ),
  'getCollectionOrdersByStudent' : IDL.Func(
      [IDL.Text, UserId],
      [IDL.Vec(CollectionOrder)],
      ['query'],
    ),
  'getCollectionQueue' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CollectionEntry)],
      ['query'],
    ),
  'getCompletedForms' : IDL.Func([IDL.Text], [IDL.Vec(BookRequest)], ['query']),
  'getInventoryLifecycle' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'bookTitle' : IDL.Text,
            'procurementRequests' : IDL.Vec(ProcurementRequest),
            'edition' : IDL.Text,
            'publisher' : IDL.Text,
            'waitingQueue' : IDL.Vec(
              IDL.Record({
                'studentId' : UserId,
                'studentName' : IDL.Text,
                'reservationDate' : Timestamp,
              })
            ),
            'bookId' : BookId,
            'availableCount' : IDL.Nat,
            'author' : IDL.Text,
            'currentHolders' : IDL.Vec(
              IDL.Record({
                'issueDate' : Timestamp,
                'studentId' : UserId,
                'studentName' : IDL.Text,
                'expectedReturnDate' : Timestamp,
              })
            ),
            'totalQuantity' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getManualBooksToPurchase' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BookRequest)],
      ['query'],
    ),
  'getMyChallans' : IDL.Func([IDL.Text], [IDL.Vec(Challan)], ['query']),
  'getMyChallansList' : IDL.Func([IDL.Text], [IDL.Vec(Challan)], ['query']),
  'getMyIssuedBooks' : IDL.Func([IDL.Text], [IDL.Vec(BookRequest)], ['query']),
  'getMyNotifications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getMyProcurements' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProcurementRequest)],
      ['query'],
    ),
  'getMyRequestOutcome' : IDL.Func(
      [IDL.Text, RequestId],
      [Result_21],
      ['query'],
    ),
  'getMyRequests' : IDL.Func([IDL.Text], [IDL.Vec(BookRequest)], ['query']),
  'getMyReservations' : IDL.Func([IDL.Text], [IDL.Vec(Reservation)], ['query']),
  'getNotificationConfig' : IDL.Func([IDL.Text], [Result_20], ['query']),
  'getNotificationDeliveryStatus' : IDL.Func(
      [IDL.Text, NotificationId],
      [Result_19],
      ['query'],
    ),
  'getPaymentStatus' : IDL.Func([IDL.Text], [Result_15], ['query']),
  'getPendingRequests' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'status' : IDL.Text,
            'requestId' : RequestId,
            'studentId' : IDL.Text,
            'studentName' : IDL.Text,
            'phoneNumber' : IDL.Text,
            'course' : IDL.Text,
            'requestDate' : Timestamp,
            'totalBooksCount' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getPendingRequestsFull' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BookRequest)],
      ['query'],
    ),
  'getQrCodeData' : IDL.Func([IDL.Text, RequestId], [IDL.Text], ['query']),
  'getRequestById' : IDL.Func([IDL.Text, RequestId], [Result_3], ['query']),
  'getRequestDetails' : IDL.Func([IDL.Text, RequestId], [Result_18], []),
  'getReservationsForBook' : IDL.Func(
      [BookId],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getReturnTimeline' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ReturnTimelineEntry)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getStudentByToken' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
  'getStudentChallans' : IDL.Func(
      [IDL.Text, UserId],
      [IDL.Vec(Challan)],
      ['query'],
    ),
  'getStudentProfile' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
  'getStudentQrUrl' : IDL.Func([UserId], [IDL.Text], ['query']),
  'getTransferHistory' : IDL.Func([IDL.Text], [IDL.Vec(Transfer)], ['query']),
  'getTransfersForBook' : IDL.Func([BookId], [IDL.Vec(Transfer)], ['query']),
  'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'importBooksFromCsv' : IDL.Func(
      [IDL.Text, IDL.Vec(BookCsvRow)],
      [Result_17],
      [],
    ),
  'initiateYearPromotion' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'isAadhaarAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmailAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([IDL.Text], [Result_4], []),
  'markBookCollected' : IDL.Func([IDL.Text, RequestId, BookId], [Result_4], []),
  'markBookReturned' : IDL.Func([IDL.Text, RequestId], [Result_3], []),
  'markNotificationRead' : IDL.Func([IDL.Text, NotificationId], [Result_4], []),
  'processYearPromotion' : IDL.Func(
      [IDL.Text, YearPromotionChoice],
      [Result_16],
      [],
    ),
  'recordPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result_15], []),
  'rejectBook' : IDL.Func(
      [IDL.Text, RequestId, BookId, IDL.Opt(IDL.Text)],
      [Result_14],
      [],
    ),
  'rejectSpecialBook' : IDL.Func(
      [IDL.Text, RequestId, IDL.Nat, IDL.Opt(IDL.Text)],
      [Result_13],
      [],
    ),
  'rejectSpecialBookRequest' : IDL.Func(
      [IDL.Text, RequestId, IDL.Text, IDL.Opt(IDL.Text)],
      [Result_4],
      [],
    ),
  'reserveBook' : IDL.Func(
      [IDL.Text, RequestId, BookId, IDL.Opt(Timestamp)],
      [Result_12],
      [],
    ),
  'searchBooks' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Book)], ['query']),
  'searchInventory' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Book)],
      ['query'],
    ),
  'searchRequests' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(BookRequest)],
      ['query'],
    ),
  'searchStudents' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(UserPublic)],
      ['query'],
    ),
  'seedBooks' : IDL.Func([IDL.Text, IDL.Vec(BookInput)], [Result_11], []),
  'sendChallanEmail' : IDL.Func(
      [IDL.Text, ChallanId],
      [IDL.Variant({ 'ok' : EmailSendResult, 'err' : IDL.Text })],
      [],
    ),
  'sendEmailNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result_10],
      [],
    ),
  'sendLifecycleEmail' : IDL.Func(
      [
        UserId,
        NotificationEventType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Result_10],
      [],
    ),
  'sendMultiChannelNotification' : IDL.Func(
      [
        IDL.Text,
        UserId,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(NotificationChannel),
      ],
      [Result_9],
      [],
    ),
  'sendOtp' : IDL.Func([IDL.Text, IDL.Text], [Result_7], []),
  'sendOtpWithEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_7], []),
  'setAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_4],
      [],
    ),
  'setReturnDate' : IDL.Func([IDL.Text, RequestId, Timestamp], [Result_4], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'studentLogout' : IDL.Func([IDL.Text], [], []),
  'studentSignupAndPay' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'transferBook' : IDL.Func(
      [IDL.Text, UserId, UserId, BookId, IDL.Opt(IDL.Text)],
      [Result_6],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerReturnReminders' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'updateBook' : IDL.Func(
      [
        IDL.Text,
        BookId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [Result_5],
      [],
    ),
  'updateBookApproval' : IDL.Func(
      [
        IDL.Text,
        RequestId,
        BookId,
        IDL.Variant({
          'RejectReservation' : IDL.Null,
          'Reject' : IDL.Null,
          'Accept' : IDL.Null,
          'AcceptReservation' : IDL.Null,
        }),
        IDL.Opt(IDL.Text),
      ],
      [Result_3],
      [],
    ),
  'updateIssuedBookStatus' : IDL.Func(
      [IDL.Text, RequestId, IDL.Bool],
      [Result_4],
      [],
    ),
  'updateManualBookStatus' : IDL.Func(
      [IDL.Text, RequestId, IDL.Text, BookDecisionStatus],
      [Result_4],
      [],
    ),
  'updateProcurementStatus' : IDL.Func(
      [IDL.Text, ProcurementId, ProcurementStatus],
      [Result_4],
      [],
    ),
  'updateRequestStatus' : IDL.Func(
      [IDL.Text, RequestId, IDL.Text],
      [Result_3],
      [],
    ),
  'updateStudent' : IDL.Func(
      [
        IDL.Text,
        UserId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Result_2],
      [],
    ),
  'updateStudentProfile' : IDL.Func(
      [IDL.Text, StudentProfileUpdate],
      [Result_2],
      [],
    ),
  'verifyOtpAndLogin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'verifyOtpWithEmail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'verifyStudentToken' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
  'waitingListAutoAssign' : IDL.Func(
      [IDL.Text, BookId, RequestId],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Text;
  const BookId = IDL.Text;
  const Book = IDL.Record({
    'title' : IDL.Text,
    'isDeleted' : IDL.Bool,
    'edition' : IDL.Text,
    'availableQuantity' : IDL.Nat,
    'publisher' : IDL.Text,
    'createdAt' : Timestamp,
    'waitingQueue' : IDL.Vec(UserId),
    'isAvailable' : IDL.Bool,
    'bookId' : BookId,
    'availableCount' : IDL.Nat,
    'author' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'currentHolders' : IDL.Vec(UserId),
    'totalQuantity' : IDL.Nat,
  });
  const Result_5 = IDL.Variant({ 'ok' : Book, 'err' : IDL.Text });
  const AdminLoginResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : IDL.Text, 'expiresAt' : Timestamp }),
    'err' : IDL.Text,
  });
  const StudentProfileUpdate = IDL.Record({
    'occupation' : IDL.Text,
    'parentContact' : IDL.Text,
    'birthDate' : IDL.Text,
    'nativePlace' : IDL.Text,
    'grandFatherName' : IDL.Text,
    'educationSpecialization' : IDL.Text,
    'surname' : IDL.Text,
    'email' : IDL.Text,
    'academicYear' : IDL.Text,
    'middleName' : IDL.Text,
    'currentLocation' : IDL.Text,
    'course' : IDL.Text,
    'courseName' : IDL.Text,
    'officialSurname' : IDL.Text,
    'educationLevel' : IDL.Text,
    'college' : IDL.Text,
    'occupationOther' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const RequestId = IDL.Text;
  const IssuedBookInfo = IDL.Record({
    'bookTitle' : IDL.Text,
    'issueDate' : Timestamp,
    'status' : IDL.Text,
    'requestId' : RequestId,
    'studentName' : IDL.Text,
    'userId' : UserId,
    'bookId' : BookId,
    'bookIds' : IDL.Vec(BookId),
    'expectedReturnDate' : Timestamp,
    'returnDate' : IDL.Opt(Timestamp),
    'returned' : IDL.Bool,
  });
  const MembershipStatus = IDL.Variant({
    'PAID' : IDL.Null,
    'NOT_PAID' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'occupation' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'studentId' : UserId,
    'parentContact' : IDL.Text,
    'birthDate' : IDL.Text,
    'nativePlace' : IDL.Text,
    'grandFatherName' : IDL.Text,
    'educationSpecialization' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'issuedBooksInfo' : IDL.Vec(IssuedBookInfo),
    'surname' : IDL.Text,
    'frozenPhone' : IDL.Bool,
    'email' : IDL.Text,
    'membershipStatus' : MembershipStatus,
    'academicYear' : IDL.Text,
    'middleName' : IDL.Text,
    'membershipStartDate' : Timestamp,
    'frozenAadhaar' : IDL.Bool,
    'paymentId' : IDL.Text,
    'currentLocation' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'phone' : IDL.Text,
    'course' : IDL.Text,
    'courseName' : IDL.Text,
    'officialSurname' : IDL.Text,
    'educationLevel' : IDL.Text,
    'profileImageUrl' : IDL.Text,
    'college' : IDL.Text,
    'occupationOther' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text });
  const BookDecisionStatus = IDL.Variant({
    'Arrived' : IDL.Null,
    'Reserved' : IDL.Null,
    'Ordered' : IDL.Null,
    'Purchased' : IDL.Null,
    'SpecialOrder' : IDL.Null,
    'ReadyForCollection' : IDL.Null,
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Issued' : IDL.Null,
    'Returned' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ProcurementId = IDL.Text;
  const BookDecision = IDL.Record({
    'decision' : BookDecisionStatus,
    'bookNumber' : IDL.Text,
    'bookName' : IDL.Text,
    'edition' : IDL.Text,
    'subject' : IDL.Text,
    'publisher' : IDL.Text,
    'procurementId' : IDL.Opt(ProcurementId),
    'currentHolderStudentId' : IDL.Opt(IDL.Text),
    'bookId' : BookId,
    'queuePosition' : IDL.Opt(IDL.Nat),
    'author' : IDL.Text,
    'procurementCreated' : IDL.Bool,
    'expectedReturnDate' : IDL.Opt(Timestamp),
    'currentHolder' : IDL.Opt(IDL.Text),
    'inventoryId' : IDL.Text,
    'reason' : IDL.Opt(IDL.Text),
  });
  const Result_14 = IDL.Variant({ 'ok' : BookDecision, 'err' : IDL.Text });
  const ChallanId = IDL.Text;
  const SpecialRequest = IDL.Record({
    'status' : BookDecisionStatus,
    'title' : IDL.Text,
    'edition' : IDL.Text,
    'publisher' : IDL.Text,
    'procurementId' : IDL.Opt(ProcurementId),
    'author' : IDL.Text,
    'expectedAvailabilityDate' : IDL.Opt(Timestamp),
    'reason' : IDL.Opt(IDL.Text),
  });
  const RequestedBookPublic = IDL.Record({
    'title' : IDL.Text,
    'edition' : IDL.Text,
    'publisher' : IDL.Text,
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const BookRequest = IDL.Record({
    'issueDate' : IDL.Opt(Timestamp),
    'status' : IDL.Text,
    'bookApprovals' : IDL.Vec(IDL.Tuple(BookId, IDL.Text)),
    'studentEmail' : IDL.Text,
    'studentAadhaar' : IDL.Text,
    'requestId' : RequestId,
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'studentYear' : IDL.Text,
    'challanId' : IDL.Opt(ChallanId),
    'requestNotes' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'specialRequests' : IDL.Vec(SpecialRequest),
    'createdAt' : Timestamp,
    'requestedBooks' : IDL.Vec(RequestedBookPublic),
    'studentPhone' : IDL.Text,
    'requestNumber' : IDL.Text,
    'collectionOrderId' : IDL.Opt(IDL.Text),
    'adminName' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'bookDecisions' : IDL.Vec(BookDecision),
    'adminId' : IDL.Opt(IDL.Text),
    'studentCourse' : IDL.Text,
    'challanData' : IDL.Text,
    'returnDate' : IDL.Opt(Timestamp),
    'returned' : IDL.Bool,
    'selectedBookIds' : IDL.Vec(BookId),
    'collectionDate' : IDL.Text,
    'collectionLocation' : IDL.Text,
    'collectionTime' : IDL.Text,
  });
  const ProcurementStatus = IDL.Variant({
    'Procured' : IDL.Null,
    'Ordered' : IDL.Null,
    'ReadyForCollection' : IDL.Null,
    'Approved' : IDL.Null,
    'Issued' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Returned' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ProcurementUrgency = IDL.Variant({
    'Required' : IDL.Null,
    'Optional' : IDL.Null,
  });
  const ProcurementRequest = IDL.Record({
    'id' : ProcurementId,
    'bookTitle' : IDL.Text,
    'status' : ProcurementStatus,
    'studentId' : UserId,
    'edition' : IDL.Opt(IDL.Text),
    'urgency' : ProcurementUrgency,
    'publisher' : IDL.Opt(IDL.Text),
    'bookId' : IDL.Opt(BookId),
    'author' : IDL.Opt(IDL.Text),
    'requestDate' : Timestamp,
  });
  const ReservationId = IDL.Text;
  const ReservationStatus = IDL.Variant({
    'Waiting' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Fulfilled' : IDL.Null,
  });
  const Reservation = IDL.Record({
    'id' : ReservationId,
    'status' : ReservationStatus,
    'studentId' : UserId,
    'bookId' : BookId,
    'expectedAvailabilityDate' : IDL.Opt(Timestamp),
    'requestDate' : Timestamp,
  });
  const BookAvailabilityDate = IDL.Record({
    'bookTitle' : IDL.Text,
    'bookId' : BookId,
    'expectedDate' : Timestamp,
  });
  const ChallanBookEntry = IDL.Record({
    'status' : BookDecisionStatus,
    'title' : IDL.Text,
    'bookNumber' : IDL.Text,
    'edition' : IDL.Text,
    'subject' : IDL.Text,
    'publisher' : IDL.Text,
    'currentHolderStudentId' : IDL.Opt(IDL.Text),
    'bookId' : BookId,
    'queuePosition' : IDL.Opt(IDL.Nat),
    'author' : IDL.Text,
    'expectedAvailabilityDate' : IDL.Opt(Timestamp),
    'expectedReturnDate' : IDL.Opt(Timestamp),
    'currentHolder' : IDL.Opt(IDL.Text),
    'reason' : IDL.Opt(IDL.Text),
  });
  const Challan = IDL.Record({
    'challanNumber' : IDL.Text,
    'trackingEvents' : IDL.Vec(IDL.Text),
    'status' : IDL.Text,
    'studentEmail' : IDL.Text,
    'signatureAdmin' : IDL.Opt(IDL.Text),
    'signatureStudent' : IDL.Opt(IDL.Text),
    'procurementRequests' : IDL.Vec(ProcurementRequest),
    'studentId' : UserId,
    'qrCodeData' : IDL.Opt(IDL.Text),
    'studentName' : IDL.Text,
    'studentYear' : IDL.Text,
    'challanId' : ChallanId,
    'reservations' : IDL.Vec(Reservation),
    'trackedBookIds' : IDL.Vec(BookId),
    'generatedAt' : Timestamp,
    'specialRequests' : IDL.Vec(SpecialRequest),
    'createdAt' : Timestamp,
    'availabilityDates' : IDL.Vec(BookAvailabilityDate),
    'studentPhone' : IDL.Text,
    'requestNumber' : RequestId,
    'orderedBooks' : IDL.Vec(ChallanBookEntry),
    'rejectedBooks' : IDL.Vec(ChallanBookEntry),
    'returnedBooks' : IDL.Vec(ChallanBookEntry),
    'arrivedBooks' : IDL.Vec(ChallanBookEntry),
    'adminName' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'bookDecisions' : IDL.Vec(BookDecision),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'qrCodeUrl' : IDL.Text,
    'approvedBooks' : IDL.Vec(ChallanBookEntry),
    'reservedBooks' : IDL.Vec(ChallanBookEntry),
    'manualBooks' : IDL.Vec(ChallanBookEntry),
    'collectionOrderNumber' : IDL.Text,
    'issuedBookIds' : IDL.Vec(BookId),
    'studentCourse' : IDL.Text,
    'issuedBooks' : IDL.Vec(ChallanBookEntry),
    'readyForCollectionBooks' : IDL.Vec(ChallanBookEntry),
    'expectedDates' : IDL.Vec(BookAvailabilityDate),
    'collectionDate' : IDL.Text,
    'collectionTime' : IDL.Text,
  });
  const Result_13 = IDL.Variant({ 'ok' : SpecialRequest, 'err' : IDL.Text });
  const Result_27 = IDL.Variant({
    'ok' : ProcurementRequest,
    'err' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result_29 = IDL.Variant({
    'ok' : IDL.Record({
      'waitingCount' : IDL.Nat,
      'available' : IDL.Bool,
      'expectedReturnDate' : IDL.Opt(Timestamp),
      'daysUntilReturn' : IDL.Opt(IDL.Int),
    }),
    'err' : IDL.Text,
  });
  const CollectionOrder = IDL.Record({
    'status' : IDL.Variant({
      'Collected' : IDL.Null,
      'Cancelled' : IDL.Null,
      'Completed' : IDL.Null,
      'Pending' : IDL.Null,
    }),
    'studentEmail' : IDL.Text,
    'requestId' : RequestId,
    'studentId' : UserId,
    'studentName' : IDL.Text,
    'studentYear' : IDL.Text,
    'challanId' : IDL.Opt(ChallanId),
    'generatedAt' : Timestamp,
    'specialRequests' : IDL.Vec(SpecialRequest),
    'studentPhone' : IDL.Text,
    'orderedBooks' : IDL.Vec(BookDecision),
    'rejectedBooks' : IDL.Vec(BookDecision),
    'orderId' : IDL.Text,
    'returnedBooks' : IDL.Vec(BookDecision),
    'arrivedBooks' : IDL.Vec(BookDecision),
    'adminName' : IDL.Text,
    'bookDecisions' : IDL.Vec(BookDecision),
    'approvedBooks' : IDL.Vec(BookDecision),
    'reservedBooks' : IDL.Vec(BookDecision),
    'studentCourse' : IDL.Text,
    'issuedBooks' : IDL.Vec(BookDecision),
    'orderNumber' : IDL.Text,
    'readyForCollectionBooks' : IDL.Vec(BookDecision),
    'collectionDate' : IDL.Text,
    'collectionLocation' : IDL.Text,
    'collectionTime' : IDL.Text,
  });
  const CompleteApprovalResult = IDL.Record({
    'collectionOrder' : CollectionOrder,
    'request' : BookRequest,
    'challan' : Challan,
  });
  const Result_26 = IDL.Variant({
    'ok' : CompleteApprovalResult,
    'err' : IDL.Text,
  });
  const AuthResult = IDL.Record({
    'token' : IDL.Text,
    'userId' : IDL.Text,
    'user' : UserPublic,
  });
  const Result_1 = IDL.Variant({ 'ok' : AuthResult, 'err' : IDL.Text });
  const WhatsAppProvider = IDL.Variant({
    'Meta' : IDL.Null,
    'Twilio' : IDL.Null,
  });
  const SmsProvider = IDL.Variant({
    'Fast2SMS' : IDL.Null,
    'Twilio' : IDL.Null,
    'MSG91' : IDL.Null,
  });
  const ProviderConfig = IDL.Record({
    'whatsAppApiKey' : IDL.Opt(IDL.Text),
    'whatsAppProvider' : IDL.Opt(WhatsAppProvider),
    'smsSenderId' : IDL.Opt(IDL.Text),
    'smsProvider' : IDL.Opt(SmsProvider),
    'smsApiKey' : IDL.Opt(IDL.Text),
    'whatsAppSenderId' : IDL.Opt(IDL.Text),
  });
  const NotificationId = IDL.Text;
  const NotificationKind = IDL.Variant({
    'BookReadyForCollection' : IDL.Null,
    'ReturnAlert' : IDL.Null,
    'CourseCompletion' : IDL.Null,
    'PaymentSuccess' : IDL.Null,
    'QueueUpdate' : IDL.Null,
    'RegistrationSuccess' : IDL.Null,
    'ChallanGenerated' : IDL.Null,
    'General' : IDL.Null,
    'BookReserved' : IDL.Null,
    'ProcurementNeeded' : IDL.Null,
    'DueDateReminder' : IDL.Null,
    'BookApproved' : IDL.Null,
    'ReservationFulfilled' : IDL.Null,
    'BookAvailable' : IDL.Null,
    'YearPromotion' : IDL.Null,
    'BookTransferred' : IDL.Null,
    'ReturnReminder' : IDL.Null,
    'BookRejected' : IDL.Null,
  });
  const DeliveryStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Demo' : IDL.Null,
    'Sent' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const NotificationChannel = IDL.Variant({
    'SMS' : IDL.Null,
    'Email' : IDL.Null,
    'WhatsApp' : IDL.Null,
    'Website' : IDL.Null,
  });
  const NotificationDeliveryStatus = IDL.Record({
    'status' : DeliveryStatus,
    'sentAt' : IDL.Opt(Timestamp),
    'error' : IDL.Opt(IDL.Text),
    'channel' : NotificationChannel,
  });
  const NotificationBookOutcome = IDL.Record({
    'status' : BookDecisionStatus,
    'bookNumber' : IDL.Text,
    'bookName' : IDL.Text,
    'edition' : IDL.Text,
    'author' : IDL.Text,
    'expectedAvailabilityDate' : IDL.Opt(Timestamp),
    'expectedReturnDate' : IDL.Opt(Timestamp),
    'currentHolder' : IDL.Opt(IDL.Text),
    'reason' : IDL.Opt(IDL.Text),
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'actionUrl' : IDL.Opt(IDL.Text),
    'userId' : IDL.Text,
    'kind' : NotificationKind,
    'deliveryStatus' : IDL.Vec(NotificationDeliveryStatus),
    'isRead' : IDL.Bool,
    'challanUrl' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'emailSent' : IDL.Bool,
    'bookOutcomes' : IDL.Vec(NotificationBookOutcome),
    'collectionDate' : IDL.Opt(IDL.Text),
    'collectionLocation' : IDL.Opt(IDL.Text),
    'collectionTime' : IDL.Opt(IDL.Text),
    'eventType' : IDL.Opt(IDL.Text),
    'readAt' : IDL.Opt(Timestamp),
  });
  const Result_9 = IDL.Variant({ 'ok' : Notification, 'err' : IDL.Text });
  const Result_3 = IDL.Variant({ 'ok' : BookRequest, 'err' : IDL.Text });
  const Result_28 = IDL.Variant({ 'ok' : Reservation, 'err' : IDL.Text });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const NotificationEventType = IDL.Text;
  const AnalyticsData = IDL.Record({
    'returnedRequests' : IDL.Nat,
    'requestsOverTime' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'waitingListCount' : IDL.Nat,
    'rejectedRequests' : IDL.Nat,
    'activeStudents' : IDL.Nat,
    'totalProcurements' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'totalReservations' : IDL.Nat,
    'booksIssued' : IDL.Nat,
    'pendingRequests' : IDL.Nat,
    'approvedRequests' : IDL.Nat,
    'booksAvailable' : IDL.Nat,
    'lowStockBooks' : IDL.Nat,
    'reservedBooks' : IDL.Nat,
    'totalBooks' : IDL.Nat,
    'booksOverdue' : IDL.Nat,
    'booksByCategory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'dueReturns' : IDL.Nat,
  });
  const AuditAction = IDL.Variant({
    'BookRequest' : IDL.Null,
    'RequestOpened' : IDL.Null,
    'ChallanGenerated' : IDL.Null,
    'BookIssue' : IDL.Null,
    'ProfileUpdate' : IDL.Null,
    'NotificationSent' : IDL.Null,
    'BookReturn' : IDL.Null,
    'ReservationCreation' : IDL.Null,
    'BookReserved' : IDL.Null,
    'RequestFinalized' : IDL.Null,
    'CollectionOrderGenerated' : IDL.Null,
    'StudentRegistration' : IDL.Null,
    'BookRejection' : IDL.Null,
    'BookApproval' : IDL.Null,
    'BookCollected' : IDL.Null,
    'AdminChange' : IDL.Null,
    'CollectionDateAssigned' : IDL.Null,
  });
  const ActorType = IDL.Variant({ 'Student' : IDL.Null, 'Admin' : IDL.Null });
  const AuditBookDecision = IDL.Record({
    'status' : BookDecisionStatus,
    'bookNumber' : IDL.Text,
    'bookName' : IDL.Text,
    'author' : IDL.Text,
    'reason' : IDL.Opt(IDL.Text),
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : AuditAction,
    'actorName' : IDL.Opt(IDL.Text),
    'actorType' : ActorType,
    'studentName' : IDL.Opt(IDL.Text),
    'resourceId' : IDL.Text,
    'requestNumber' : IDL.Opt(IDL.Text),
    'actorId' : IDL.Text,
    'adminName' : IDL.Opt(IDL.Text),
    'resourceType' : IDL.Opt(IDL.Text),
    'bookDecisions' : IDL.Vec(AuditBookDecision),
    'timestamp' : Timestamp,
    'details' : IDL.Opt(IDL.Text),
    'userAgent' : IDL.Opt(IDL.Text),
    'ipAddress' : IDL.Opt(IDL.Text),
  });
  const Result_25 = IDL.Variant({
    'ok' : IDL.Vec(AuditEntry),
    'err' : IDL.Text,
  });
  const Result_24 = IDL.Variant({ 'ok' : Challan, 'err' : IDL.Text });
  const ChallanPdfData = IDL.Record({
    'adminSignaturePlaceholder' : IDL.Text,
    'studentSignaturePlaceholder' : IDL.Text,
    'qrCodeUrl' : IDL.Text,
    'collectionOrderNumber' : IDL.Text,
    'challan' : Challan,
    'collectionDate' : IDL.Text,
    'collectionLocation' : IDL.Text,
    'collectionTime' : IDL.Text,
  });
  const Result_23 = IDL.Variant({ 'ok' : ChallanPdfData, 'err' : IDL.Text });
  const Result_22 = IDL.Variant({ 'ok' : CollectionOrder, 'err' : IDL.Text });
  const CollectionEntry = IDL.Record({
    'bookTitle' : IDL.Text,
    'requestId' : RequestId,
    'studentId' : UserId,
    'studentName' : IDL.Text,
    'bookId' : BookId,
    'collectionDeadline' : Timestamp,
    'approvalDate' : Timestamp,
    'entryId' : IDL.Text,
    'collected' : IDL.Bool,
  });
  const RequestOutcome = IDL.Record({
    'requestId' : RequestId,
    'challanId' : IDL.Opt(ChallanId),
    'requestNumber' : IDL.Text,
    'rejectedBooks' : IDL.Vec(BookDecision),
    'collectionOrderId' : IDL.Opt(IDL.Text),
    'approvedBooks' : IDL.Vec(BookDecision),
    'reservedBooks' : IDL.Vec(BookDecision),
    'overallStatus' : IDL.Text,
    'collectionDate' : IDL.Text,
    'collectionLocation' : IDL.Text,
    'collectionTime' : IDL.Text,
  });
  const Result_21 = IDL.Variant({ 'ok' : RequestOutcome, 'err' : IDL.Text });
  const Result_20 = IDL.Variant({
    'ok' : IDL.Record({
      'demoMode' : IDL.Bool,
      'whatsAppConfigured' : IDL.Bool,
      'smsConfigured' : IDL.Bool,
    }),
    'err' : IDL.Text,
  });
  const Result_19 = IDL.Variant({
    'ok' : IDL.Record({
      'pending' : IDL.Nat,
      'demo' : IDL.Nat,
      'sent' : IDL.Nat,
      'failed' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const PaymentId = IDL.Text;
  const Payment = IDL.Record({
    'status' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'paymentId' : PaymentId,
    'stripePaymentId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Result_15 = IDL.Variant({ 'ok' : Payment, 'err' : IDL.Text });
  const BookDetailView = IDL.Record({
    'title' : IDL.Text,
    'decision' : IDL.Opt(BookDecision),
    'bookNumber' : IDL.Text,
    'edition' : IDL.Text,
    'subject' : IDL.Text,
    'publisher' : IDL.Text,
    'queueLength' : IDL.Nat,
    'bookId' : BookId,
    'author' : IDL.Text,
    'expectedReturnDate' : IDL.Opt(Timestamp),
    'currentHolder' : IDL.Opt(IDL.Text),
    'inventoryId' : IDL.Text,
    'availabilityStatus' : IDL.Text,
  });
  const RequestDetails = IDL.Record({
    'request' : BookRequest,
    'specialRequests' : IDL.Vec(SpecialRequest),
    'student' : UserPublic,
    'books' : IDL.Vec(BookDetailView),
  });
  const Result_18 = IDL.Variant({ 'ok' : RequestDetails, 'err' : IDL.Text });
  const ReturnTimelineEntry = IDL.Record({
    'issueDate' : Timestamp,
    'requestId' : RequestId,
    'studentId' : UserId,
    'studentName' : IDL.Text,
    'bookTitles' : IDL.Vec(IDL.Text),
    'daysUntilReturn' : IDL.Int,
    'phone' : IDL.Text,
    'studentCourse' : IDL.Text,
    'returnDate' : IDL.Opt(Timestamp),
    'returned' : IDL.Bool,
    'nextReservedStudent' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TransferId = IDL.Text;
  const Transfer = IDL.Record({
    'id' : TransferId,
    'transferDate' : Timestamp,
    'challanId' : IDL.Opt(ChallanId),
    'bookId' : BookId,
    'toStudentId' : UserId,
    'fromStudentId' : UserId,
    'adminNotes' : IDL.Opt(IDL.Text),
  });
  const BookCsvRow = IDL.Record({
    'title' : IDL.Text,
    'availableCopies' : IDL.Nat,
    'edition' : IDL.Text,
    'publisher' : IDL.Text,
    'author' : IDL.Text,
    'totalCopies' : IDL.Nat,
    'category' : IDL.Text,
  });
  const CsvImportResult = IDL.Record({
    'skipped' : IDL.Nat,
    'errors' : IDL.Vec(IDL.Text),
    'processed' : IDL.Nat,
  });
  const Result_17 = IDL.Variant({ 'ok' : CsvImportResult, 'err' : IDL.Text });
  const YearPromotionChoice = IDL.Variant({
    'ContinueNextYear' : IDL.Null,
    'ReturnBooks' : IDL.Null,
  });
  const Result_16 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Result_12 = IDL.Variant({
    'ok' : IDL.Record({
      'reservation' : Reservation,
      'queuePosition' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const BookInput = IDL.Record({
    'title' : IDL.Text,
    'edition' : IDL.Text,
    'publisher' : IDL.Text,
    'author' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Result_11 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const EmailSendResult = IDL.Record({
    'messageId' : IDL.Opt(IDL.Text),
    'sentAt' : Timestamp,
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const Result_10 = IDL.Variant({ 'ok' : EmailSendResult, 'err' : IDL.Text });
  const Result_7 = IDL.Variant({
    'ok' : IDL.Record({ 'otp' : IDL.Text, 'demo' : IDL.Bool }),
    'err' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const Result_6 = IDL.Variant({ 'ok' : Transfer, 'err' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const CollectionOrderId = IDL.Text;
  const WaitingListAssignment = IDL.Record({
    'assigned' : IDL.Bool,
    'nextStudentId' : IDL.Opt(UserId),
    'newRequestId' : IDL.Opt(RequestId),
    'nextStudentName' : IDL.Opt(IDL.Text),
    'collectionOrderId' : IDL.Opt(CollectionOrderId),
  });
  const Result = IDL.Variant({
    'ok' : WaitingListAssignment,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Result_5],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [AdminLoginResult], []),
    'adminUpdateStudentProfile' : IDL.Func(
        [IDL.Text, UserId, StudentProfileUpdate],
        [Result_2],
        [],
      ),
    'approveBook' : IDL.Func([IDL.Text, RequestId, BookId], [Result_14], []),
    'approveBookAndUpdateChallan' : IDL.Func(
        [
          IDL.Text,
          RequestId,
          BookId,
          IDL.Variant({
            'RejectReservation' : IDL.Null,
            'Reject' : IDL.Null,
            'Accept' : IDL.Null,
            'AcceptReservation' : IDL.Null,
          }),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'request' : BookRequest, 'challan' : Challan }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'approveSpecialBook' : IDL.Func(
        [IDL.Text, RequestId, IDL.Nat],
        [Result_13],
        [],
      ),
    'approveSpecialBookRequest' : IDL.Func(
        [IDL.Text, RequestId, IDL.Text],
        [Result_27],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelReservation' : IDL.Func([IDL.Text, ReservationId], [Result_4], []),
    'checkBookAvailability' : IDL.Func([BookId], [Result_29], ['query']),
    'completeApproval' : IDL.Func(
        [IDL.Text, RequestId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_26],
        [],
      ),
    'completeProfileAndPay' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Result_1],
        [],
      ),
    'configureNotificationProviders' : IDL.Func(
        [IDL.Text, ProviderConfig],
        [Result_4],
        [],
      ),
    'createAdminNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_9],
        [],
      ),
    'createBookRequest' : IDL.Func(
        [IDL.Text, IDL.Vec(BookId), IDL.Vec(RequestedBookPublic)],
        [Result_3],
        [],
      ),
    'createBookReservation' : IDL.Func(
        [IDL.Text, BookId, IDL.Opt(Timestamp)],
        [Result_28],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createProcurementRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(BookId),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          ProcurementUrgency,
        ],
        [Result_27],
        [],
      ),
    'createReservation' : IDL.Func(
        [IDL.Text, BookId, IDL.Opt(Timestamp)],
        [Result_28],
        [],
      ),
    'createStudentNotification' : IDL.Func(
        [
          IDL.Text,
          UserId,
          NotificationEventType,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [Result_9],
        [],
      ),
    'createUrgentProcurementRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(BookId),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Result_27],
        [],
      ),
    'deleteBook' : IDL.Func([IDL.Text, BookId], [Result_4], []),
    'finalizeRequest' : IDL.Func(
        [IDL.Text, RequestId, IDL.Text, IDL.Text, IDL.Text],
        [Result_26],
        [],
      ),
    'generateChallanForRequest' : IDL.Func(
        [IDL.Text, RequestId, IDL.Text],
        [IDL.Variant({ 'ok' : Challan, 'err' : IDL.Text })],
        [],
      ),
    'getAdminNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getAdminPendingCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getAdminReturnAlerts' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'bookTitle' : IDL.Text,
              'requestId' : RequestId,
              'studentId' : UserId,
              'studentName' : IDL.Text,
              'urgency' : IDL.Text,
              'bookId' : BookId,
              'daysUntilReturn' : IDL.Int,
              'returnDate' : IDL.Opt(Timestamp),
              'nextReservedStudent' : IDL.Opt(
                IDL.Record({ 'studentId' : UserId, 'studentName' : IDL.Text })
              ),
            })
          ),
        ],
        ['query'],
      ),
    'getAllBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'getAllChallans' : IDL.Func([IDL.Text], [IDL.Vec(Challan)], ['query']),
    'getAllCollectionOrders' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CollectionOrder)],
        ['query'],
      ),
    'getAllProcurements' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProcurementRequest)],
        ['query'],
      ),
    'getAllRequests' : IDL.Func([IDL.Text], [IDL.Vec(BookRequest)], ['query']),
    'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserPublic)], ['query']),
    'getAnalyticsData' : IDL.Func([IDL.Text], [AnalyticsData], ['query']),
    'getAuditLog' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(AuditAction),
          IDL.Opt(Timestamp),
          IDL.Opt(Timestamp),
        ],
        [Result_25],
        ['query'],
      ),
    'getAuditLogs' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(AuditAction),
          IDL.Opt(Timestamp),
          IDL.Opt(Timestamp),
          IDL.Nat,
        ],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'getAvailableDropOptions' : IDL.Func(
        [],
        [
          IDL.Record({
            'villages' : IDL.Vec(IDL.Text),
            'surnames' : IDL.Vec(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getBookById' : IDL.Func([BookId], [Result_5], ['query']),
    'getBookLifecycleFlow' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'bookTitle' : IDL.Text,
              'bookId' : BookId,
              'currentHolder' : IDL.Opt(
                IDL.Record({
                  'issueDate' : Timestamp,
                  'userId' : UserId,
                  'name' : IDL.Text,
                  'returnDate' : IDL.Opt(Timestamp),
                })
              ),
              'nextReservedStudent' : IDL.Opt(
                IDL.Record({
                  'reservationDate' : Timestamp,
                  'userId' : UserId,
                  'name' : IDL.Text,
                })
              ),
            })
          ),
        ],
        ['query'],
      ),
    'getBookRecommendations' : IDL.Func([BookId], [IDL.Vec(Book)], ['query']),
    'getBooksReturningByDate' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'bookTitle' : IDL.Text,
              'requestId' : RequestId,
              'studentId' : UserId,
              'studentName' : IDL.Text,
              'bookId' : BookId,
              'daysUntilReturn' : IDL.Int,
              'returnDate' : Timestamp,
              'nextReservedStudent' : IDL.Opt(
                IDL.Record({ 'studentId' : UserId, 'studentName' : IDL.Text })
              ),
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getChallan' : IDL.Func([IDL.Text, ChallanId], [Result_24], ['query']),
    'getChallanById' : IDL.Func(
        [IDL.Text, ChallanId],
        [IDL.Opt(Challan)],
        ['query'],
      ),
    'getChallanPdfData' : IDL.Func(
        [IDL.Text, ChallanId],
        [Result_23],
        ['query'],
      ),
    'getCollectionOrder' : IDL.Func(
        [IDL.Text, RequestId],
        [Result_22],
        ['query'],
      ),
    'getCollectionOrderByNumber' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Result_22],
        ['query'],
      ),
    'getCollectionOrdersByAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CollectionOrder)],
        ['query'],
      ),
    'getCollectionOrdersByStudent' : IDL.Func(
        [IDL.Text, UserId],
        [IDL.Vec(CollectionOrder)],
        ['query'],
      ),
    'getCollectionQueue' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CollectionEntry)],
        ['query'],
      ),
    'getCompletedForms' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookRequest)],
        ['query'],
      ),
    'getInventoryLifecycle' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'bookTitle' : IDL.Text,
              'procurementRequests' : IDL.Vec(ProcurementRequest),
              'edition' : IDL.Text,
              'publisher' : IDL.Text,
              'waitingQueue' : IDL.Vec(
                IDL.Record({
                  'studentId' : UserId,
                  'studentName' : IDL.Text,
                  'reservationDate' : Timestamp,
                })
              ),
              'bookId' : BookId,
              'availableCount' : IDL.Nat,
              'author' : IDL.Text,
              'currentHolders' : IDL.Vec(
                IDL.Record({
                  'issueDate' : Timestamp,
                  'studentId' : UserId,
                  'studentName' : IDL.Text,
                  'expectedReturnDate' : Timestamp,
                })
              ),
              'totalQuantity' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getManualBooksToPurchase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookRequest)],
        ['query'],
      ),
    'getMyChallans' : IDL.Func([IDL.Text], [IDL.Vec(Challan)], ['query']),
    'getMyChallansList' : IDL.Func([IDL.Text], [IDL.Vec(Challan)], ['query']),
    'getMyIssuedBooks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookRequest)],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getMyProcurements' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProcurementRequest)],
        ['query'],
      ),
    'getMyRequestOutcome' : IDL.Func(
        [IDL.Text, RequestId],
        [Result_21],
        ['query'],
      ),
    'getMyRequests' : IDL.Func([IDL.Text], [IDL.Vec(BookRequest)], ['query']),
    'getMyReservations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getNotificationConfig' : IDL.Func([IDL.Text], [Result_20], ['query']),
    'getNotificationDeliveryStatus' : IDL.Func(
        [IDL.Text, NotificationId],
        [Result_19],
        ['query'],
      ),
    'getPaymentStatus' : IDL.Func([IDL.Text], [Result_15], ['query']),
    'getPendingRequests' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'status' : IDL.Text,
              'requestId' : RequestId,
              'studentId' : IDL.Text,
              'studentName' : IDL.Text,
              'phoneNumber' : IDL.Text,
              'course' : IDL.Text,
              'requestDate' : Timestamp,
              'totalBooksCount' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getPendingRequestsFull' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookRequest)],
        ['query'],
      ),
    'getQrCodeData' : IDL.Func([IDL.Text, RequestId], [IDL.Text], ['query']),
    'getRequestById' : IDL.Func([IDL.Text, RequestId], [Result_3], ['query']),
    'getRequestDetails' : IDL.Func([IDL.Text, RequestId], [Result_18], []),
    'getReservationsForBook' : IDL.Func(
        [BookId],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getReturnTimeline' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReturnTimelineEntry)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getStudentByToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserPublic)],
        ['query'],
      ),
    'getStudentChallans' : IDL.Func(
        [IDL.Text, UserId],
        [IDL.Vec(Challan)],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
    'getStudentQrUrl' : IDL.Func([UserId], [IDL.Text], ['query']),
    'getTransferHistory' : IDL.Func([IDL.Text], [IDL.Vec(Transfer)], ['query']),
    'getTransfersForBook' : IDL.Func([BookId], [IDL.Vec(Transfer)], ['query']),
    'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'importBooksFromCsv' : IDL.Func(
        [IDL.Text, IDL.Vec(BookCsvRow)],
        [Result_17],
        [],
      ),
    'initiateYearPromotion' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'isAadhaarAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmailAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([IDL.Text], [Result_4], []),
    'markBookCollected' : IDL.Func(
        [IDL.Text, RequestId, BookId],
        [Result_4],
        [],
      ),
    'markBookReturned' : IDL.Func([IDL.Text, RequestId], [Result_3], []),
    'markNotificationRead' : IDL.Func(
        [IDL.Text, NotificationId],
        [Result_4],
        [],
      ),
    'processYearPromotion' : IDL.Func(
        [IDL.Text, YearPromotionChoice],
        [Result_16],
        [],
      ),
    'recordPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result_15], []),
    'rejectBook' : IDL.Func(
        [IDL.Text, RequestId, BookId, IDL.Opt(IDL.Text)],
        [Result_14],
        [],
      ),
    'rejectSpecialBook' : IDL.Func(
        [IDL.Text, RequestId, IDL.Nat, IDL.Opt(IDL.Text)],
        [Result_13],
        [],
      ),
    'rejectSpecialBookRequest' : IDL.Func(
        [IDL.Text, RequestId, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_4],
        [],
      ),
    'reserveBook' : IDL.Func(
        [IDL.Text, RequestId, BookId, IDL.Opt(Timestamp)],
        [Result_12],
        [],
      ),
    'searchBooks' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Book)], ['query']),
    'searchInventory' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Book)],
        ['query'],
      ),
    'searchRequests' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(BookRequest)],
        ['query'],
      ),
    'searchStudents' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(UserPublic)],
        ['query'],
      ),
    'seedBooks' : IDL.Func([IDL.Text, IDL.Vec(BookInput)], [Result_11], []),
    'sendChallanEmail' : IDL.Func(
        [IDL.Text, ChallanId],
        [IDL.Variant({ 'ok' : EmailSendResult, 'err' : IDL.Text })],
        [],
      ),
    'sendEmailNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_10],
        [],
      ),
    'sendLifecycleEmail' : IDL.Func(
        [
          UserId,
          NotificationEventType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Result_10],
        [],
      ),
    'sendMultiChannelNotification' : IDL.Func(
        [
          IDL.Text,
          UserId,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(NotificationChannel),
        ],
        [Result_9],
        [],
      ),
    'sendOtp' : IDL.Func([IDL.Text, IDL.Text], [Result_7], []),
    'sendOtpWithEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_7],
        [],
      ),
    'setAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_4],
        [],
      ),
    'setReturnDate' : IDL.Func(
        [IDL.Text, RequestId, Timestamp],
        [Result_4],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'studentLogout' : IDL.Func([IDL.Text], [], []),
    'studentSignupAndPay' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'transferBook' : IDL.Func(
        [IDL.Text, UserId, UserId, BookId, IDL.Opt(IDL.Text)],
        [Result_6],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerReturnReminders' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'updateBook' : IDL.Func(
        [
          IDL.Text,
          BookId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [Result_5],
        [],
      ),
    'updateBookApproval' : IDL.Func(
        [
          IDL.Text,
          RequestId,
          BookId,
          IDL.Variant({
            'RejectReservation' : IDL.Null,
            'Reject' : IDL.Null,
            'Accept' : IDL.Null,
            'AcceptReservation' : IDL.Null,
          }),
          IDL.Opt(IDL.Text),
        ],
        [Result_3],
        [],
      ),
    'updateIssuedBookStatus' : IDL.Func(
        [IDL.Text, RequestId, IDL.Bool],
        [Result_4],
        [],
      ),
    'updateManualBookStatus' : IDL.Func(
        [IDL.Text, RequestId, IDL.Text, BookDecisionStatus],
        [Result_4],
        [],
      ),
    'updateProcurementStatus' : IDL.Func(
        [IDL.Text, ProcurementId, ProcurementStatus],
        [Result_4],
        [],
      ),
    'updateRequestStatus' : IDL.Func(
        [IDL.Text, RequestId, IDL.Text],
        [Result_3],
        [],
      ),
    'updateStudent' : IDL.Func(
        [
          IDL.Text,
          UserId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Result_2],
        [],
      ),
    'updateStudentProfile' : IDL.Func(
        [IDL.Text, StudentProfileUpdate],
        [Result_2],
        [],
      ),
    'verifyOtpAndLogin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'verifyOtpWithEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'verifyStudentToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserPublic)],
        ['query'],
      ),
    'waitingListAutoAssign' : IDL.Func(
        [IDL.Text, BookId, RequestId],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };